// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f action_kind_enum.go

package computer

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// ActionKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ActionKind struct {
	actionKind
}

// actionKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ActionKind type.
type actionKindsContainer struct {
	NAVIGATE ActionKind
	CLICK    ActionKind
	FILL     ActionKind
	PRESS    ActionKind
	SCROLL   ActionKind
}

// ActionKinds is a main entry point using the ActionKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ActionKinds = actionKindsContainer{
	NAVIGATE: ActionKind{
		actionKind: navigate,
	},
	CLICK: ActionKind{
		actionKind: click,
	},
	FILL: ActionKind{
		actionKind: fill,
	},
	PRESS: ActionKind{
		actionKind: press,
	},
	SCROLL: ActionKind{
		actionKind: scroll,
	},
}

// invalidActionKind is an invalid sentinel value for ActionKind
var invalidActionKind = ActionKind{
	actionKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a actionKindsContainer) allSlice() []ActionKind {
	return []ActionKind{
		ActionKinds.NAVIGATE,
		ActionKinds.CLICK,
		ActionKinds.FILL,
		ActionKinds.PRESS,
		ActionKinds.SCROLL,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a actionKindsContainer) All() iter.Seq[ActionKind] {
	return func(yield func(ActionKind) bool) {
		for _, v := range a.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseActionKind = errors.New("invalid input provided to parse to ActionKind")

// ParseActionKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseActionKind(input any) (ActionKind, error) {
	switch v := input.(type) {
	case ActionKind:
		return v, nil
	case string:
		if result := stringToActionKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToActionKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToActionKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToActionKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidActionKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidActionKind, fmt.Errorf("%w: invalid value %v", ErrParseActionKind, input)
}

// actionKindsNameMap is a map of enum values to their ActionKind representation
// It is used to convert string representations of enum values into their ActionKind representation.
var actionKindsNameMap = map[string]ActionKind{
	"navigate": ActionKinds.NAVIGATE,
	"click":    ActionKinds.CLICK,
	"fill":     ActionKinds.FILL,
	"press":    ActionKinds.PRESS,
	"scroll":   ActionKinds.SCROLL,
}

// stringToActionKind converts a string representation of an enum value into its ActionKind representation
// It returns a pointer to the ActionKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToActionKind(s string) *ActionKind {
	if t, ok := actionKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToActionKind converts a numeric value to a ActionKind
// It returns a pointer to the ActionKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToActionKind[T constraints.Integer | constraints.Float](num T) *ActionKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ActionKinds.allSlice()) {
		return nil
	}
	result := ActionKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveActionKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveActionKinds(f func(ActionKind)) {
	for _, p := range ActionKinds.allSlice() {
		f(p)
	}
}

// validActionKinds is a map of enum values to their validity
var validActionKinds = map[ActionKind]bool{
	ActionKinds.NAVIGATE: true,
	ActionKinds.CLICK:    true,
	ActionKinds.FILL:     true,
	ActionKinds.PRESS:    true,
	ActionKinds.SCROLL:   true,
}

// IsValid checks whether the ActionKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (a ActionKind) IsValid() bool {
	return validActionKinds[a]
}

// MarshalJSON implements the json.Marshaler interface for ActionKind.
// It returns the JSON representation of the enum value as a byte slice.
func (a ActionKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ActionKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (a *ActionKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newa, err := ParseActionKind(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ActionKind.
// It returns the string representation of the enum value as a byte slice
func (a ActionKind) MarshalText() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ActionKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *ActionKind) UnmarshalText(by []byte) error {
	newa, err := ParseActionKind(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Scan implements the database/sql.Scanner interface for ActionKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (a *ActionKind) Scan(value any) error {
	newa, err := ParseActionKind(value)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ActionKind.
// It returns the string representation of the enum value.
func (a ActionKind) Value() (driver.Value, error) {
	return a.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ActionKind.
// It returns the binary representation of the enum value as a byte slice.
func (a ActionKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ActionKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *ActionKind) UnmarshalBinary(by []byte) error {
	newa, err := ParseActionKind(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ActionKind.
// It returns the string representation of the enum value.
func (a ActionKind) MarshalYAML() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (a *ActionKind) UnmarshalYAML(by []byte) error {
	newa, err := ParseActionKind(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// actionkindNames is a constant string slice containing all enum values cononical absolute names
const actionkindNames = "navigateclickfillpressscroll"

// actionkindNamesMap is a map of enum values to their canonical absolute
// name positions within the actionkindNames string slice
var actionkindNamesMap = map[ActionKind]string{
	ActionKinds.NAVIGATE: actionkindNames[0:8],
	ActionKinds.CLICK:    actionkindNames[8:13],
	ActionKinds.FILL:     actionkindNames[13:17],
	ActionKinds.PRESS:    actionkindNames[17:22],
	ActionKinds.SCROLL:   actionkindNames[22:28],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (a ActionKind) String() string {
	if str, ok := actionkindNamesMap[a]; ok {
		return str
	}
	return fmt.Sprintf("actionkind(%d)", a.actionKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[navigate]
	_ = x[click-1]
	_ = x[fill-2]
	_ = x[press-3]
	_ = x[scroll-4]
}
