// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f surface_kind_enum.go

package computer

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// SurfaceKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type SurfaceKind struct {
	surfaceKind
}

// surfaceKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the SurfaceKind type.
type surfaceKindsContainer struct {
	BROWSER  SurfaceKind
	DESKTOP  SurfaceKind
	TERMINAL SurfaceKind
}

// SurfaceKinds is a main entry point using the SurfaceKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var SurfaceKinds = surfaceKindsContainer{
	BROWSER: SurfaceKind{
		surfaceKind: browser,
	},
	DESKTOP: SurfaceKind{
		surfaceKind: desktop,
	},
	TERMINAL: SurfaceKind{
		surfaceKind: terminal,
	},
}

// invalidSurfaceKind is an invalid sentinel value for SurfaceKind
var invalidSurfaceKind = SurfaceKind{
	surfaceKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s surfaceKindsContainer) allSlice() []SurfaceKind {
	return []SurfaceKind{
		SurfaceKinds.BROWSER,
		SurfaceKinds.DESKTOP,
		SurfaceKinds.TERMINAL,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s surfaceKindsContainer) All() iter.Seq[SurfaceKind] {
	return func(yield func(SurfaceKind) bool) {
		for _, v := range s.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseSurfaceKind = errors.New("invalid input provided to parse to SurfaceKind")

// ParseSurfaceKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseSurfaceKind(input any) (SurfaceKind, error) {
	switch v := input.(type) {
	case SurfaceKind:
		return v, nil
	case string:
		if result := stringToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToSurfaceKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToSurfaceKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToSurfaceKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidSurfaceKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidSurfaceKind, fmt.Errorf("%w: invalid value %v", ErrParseSurfaceKind, input)
}

// surfaceKindsNameMap is a map of enum values to their SurfaceKind representation
// It is used to convert string representations of enum values into their SurfaceKind representation.
var surfaceKindsNameMap = map[string]SurfaceKind{
	"browser":  SurfaceKinds.BROWSER,
	"desktop":  SurfaceKinds.DESKTOP,
	"terminal": SurfaceKinds.TERMINAL,
}

// stringToSurfaceKind converts a string representation of an enum value into its SurfaceKind representation
// It returns a pointer to the SurfaceKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToSurfaceKind(s string) *SurfaceKind {
	if t, ok := surfaceKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToSurfaceKind converts a numeric value to a SurfaceKind
// It returns a pointer to the SurfaceKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToSurfaceKind[T constraints.Integer | constraints.Float](num T) *SurfaceKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(SurfaceKinds.allSlice()) {
		return nil
	}
	result := SurfaceKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveSurfaceKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveSurfaceKinds(f func(SurfaceKind)) {
	for _, p := range SurfaceKinds.allSlice() {
		f(p)
	}
}

// validSurfaceKinds is a map of enum values to their validity
var validSurfaceKinds = map[SurfaceKind]bool{
	SurfaceKinds.BROWSER:  true,
	SurfaceKinds.DESKTOP:  true,
	SurfaceKinds.TERMINAL: true,
}

// IsValid checks whether the SurfaceKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (s SurfaceKind) IsValid() bool {
	return validSurfaceKinds[s]
}

// MarshalJSON implements the json.Marshaler interface for SurfaceKind.
// It returns the JSON representation of the enum value as a byte slice.
func (s SurfaceKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SurfaceKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (s *SurfaceKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	news, err := ParseSurfaceKind(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for SurfaceKind.
// It returns the string representation of the enum value as a byte slice
func (s SurfaceKind) MarshalText() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SurfaceKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SurfaceKind) UnmarshalText(by []byte) error {
	news, err := ParseSurfaceKind(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Scan implements the database/sql.Scanner interface for SurfaceKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (s *SurfaceKind) Scan(value any) error {
	news, err := ParseSurfaceKind(value)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Value implements the database/sql/driver.Valuer interface for SurfaceKind.
// It returns the string representation of the enum value.
func (s SurfaceKind) Value() (driver.Value, error) {
	return s.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for SurfaceKind.
// It returns the binary representation of the enum value as a byte slice.
func (s SurfaceKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for SurfaceKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *SurfaceKind) UnmarshalBinary(by []byte) error {
	news, err := ParseSurfaceKind(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for SurfaceKind.
// It returns the string representation of the enum value.
func (s SurfaceKind) MarshalYAML() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (s *SurfaceKind) UnmarshalYAML(by []byte) error {
	news, err := ParseSurfaceKind(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// surfacekindNames is a constant string slice containing all enum values cononical absolute names
const surfacekindNames = "browserdesktopterminal"

// surfacekindNamesMap is a map of enum values to their canonical absolute
// name positions within the surfacekindNames string slice
var surfacekindNamesMap = map[SurfaceKind]string{
	SurfaceKinds.BROWSER:  surfacekindNames[0:7],
	SurfaceKinds.DESKTOP:  surfacekindNames[7:14],
	SurfaceKinds.TERMINAL: surfacekindNames[14:22],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (s SurfaceKind) String() string {
	if str, ok := surfacekindNamesMap[s]; ok {
		return str
	}
	return fmt.Sprintf("surfacekind(%d)", s.surfaceKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[browser]
	_ = x[desktop-1]
	_ = x[terminal-2]
}
