// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f trigger_kind_enum.go

package computer

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// TriggerKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type TriggerKind struct {
	triggerKind
}

// triggerKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the TriggerKind type.
type triggerKindsContainer struct {
	VISIBLE            TriggerKind
	HIDDEN             TriggerKind
	FOCUSED            TriggerKind
	TEXTPRESENT        TriggerKind
	VALUEEQUALS        TriggerKind
	URLMATCHES         TriggerKind
	NAVIGATIONCOMPLETE TriggerKind
	SURFACESTABLE      TriggerKind
}

// TriggerKinds is a main entry point using the TriggerKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var TriggerKinds = triggerKindsContainer{
	VISIBLE: TriggerKind{
		triggerKind: visible,
	},
	HIDDEN: TriggerKind{
		triggerKind: hidden,
	},
	FOCUSED: TriggerKind{
		triggerKind: focused,
	},
	TEXTPRESENT: TriggerKind{
		triggerKind: textPresent,
	},
	VALUEEQUALS: TriggerKind{
		triggerKind: valueEquals,
	},
	URLMATCHES: TriggerKind{
		triggerKind: urlMatches,
	},
	NAVIGATIONCOMPLETE: TriggerKind{
		triggerKind: navigationComplete,
	},
	SURFACESTABLE: TriggerKind{
		triggerKind: surfaceStable,
	},
}

// invalidTriggerKind is an invalid sentinel value for TriggerKind
var invalidTriggerKind = TriggerKind{
	triggerKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t triggerKindsContainer) allSlice() []TriggerKind {
	return []TriggerKind{
		TriggerKinds.VISIBLE,
		TriggerKinds.HIDDEN,
		TriggerKinds.FOCUSED,
		TriggerKinds.TEXTPRESENT,
		TriggerKinds.VALUEEQUALS,
		TriggerKinds.URLMATCHES,
		TriggerKinds.NAVIGATIONCOMPLETE,
		TriggerKinds.SURFACESTABLE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t triggerKindsContainer) All() iter.Seq[TriggerKind] {
	return func(yield func(TriggerKind) bool) {
		for _, v := range t.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseTriggerKind = errors.New("invalid input provided to parse to TriggerKind")

// ParseTriggerKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseTriggerKind(input any) (TriggerKind, error) {
	switch v := input.(type) {
	case TriggerKind:
		return v, nil
	case string:
		if result := stringToTriggerKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToTriggerKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToTriggerKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToTriggerKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidTriggerKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidTriggerKind, fmt.Errorf("%w: invalid value %v", ErrParseTriggerKind, input)
}

// triggerKindsNameMap is a map of enum values to their TriggerKind representation
// It is used to convert string representations of enum values into their TriggerKind representation.
var triggerKindsNameMap = map[string]TriggerKind{
	"visible":             TriggerKinds.VISIBLE,
	"hidden":              TriggerKinds.HIDDEN,
	"focused":             TriggerKinds.FOCUSED,
	"text_present":        TriggerKinds.TEXTPRESENT,
	"value_equals":        TriggerKinds.VALUEEQUALS,
	"url_matches":         TriggerKinds.URLMATCHES,
	"navigation_complete": TriggerKinds.NAVIGATIONCOMPLETE,
	"surface_stable":      TriggerKinds.SURFACESTABLE,
}

// stringToTriggerKind converts a string representation of an enum value into its TriggerKind representation
// It returns a pointer to the TriggerKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToTriggerKind(s string) *TriggerKind {
	if t, ok := triggerKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToTriggerKind converts a numeric value to a TriggerKind
// It returns a pointer to the TriggerKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToTriggerKind[T constraints.Integer | constraints.Float](num T) *TriggerKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(TriggerKinds.allSlice()) {
		return nil
	}
	result := TriggerKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveTriggerKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveTriggerKinds(f func(TriggerKind)) {
	for _, p := range TriggerKinds.allSlice() {
		f(p)
	}
}

// validTriggerKinds is a map of enum values to their validity
var validTriggerKinds = map[TriggerKind]bool{
	TriggerKinds.VISIBLE:            true,
	TriggerKinds.HIDDEN:             true,
	TriggerKinds.FOCUSED:            true,
	TriggerKinds.TEXTPRESENT:        true,
	TriggerKinds.VALUEEQUALS:        true,
	TriggerKinds.URLMATCHES:         true,
	TriggerKinds.NAVIGATIONCOMPLETE: true,
	TriggerKinds.SURFACESTABLE:      true,
}

// IsValid checks whether the TriggerKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (t TriggerKind) IsValid() bool {
	return validTriggerKinds[t]
}

// MarshalJSON implements the json.Marshaler interface for TriggerKind.
// It returns the JSON representation of the enum value as a byte slice.
func (t TriggerKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for TriggerKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (t *TriggerKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newt, err := ParseTriggerKind(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for TriggerKind.
// It returns the string representation of the enum value as a byte slice
func (t TriggerKind) MarshalText() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TriggerKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TriggerKind) UnmarshalText(by []byte) error {
	newt, err := ParseTriggerKind(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Scan implements the database/sql.Scanner interface for TriggerKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (t *TriggerKind) Scan(value any) error {
	newt, err := ParseTriggerKind(value)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Value implements the database/sql/driver.Valuer interface for TriggerKind.
// It returns the string representation of the enum value.
func (t TriggerKind) Value() (driver.Value, error) {
	return t.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for TriggerKind.
// It returns the binary representation of the enum value as a byte slice.
func (t TriggerKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for TriggerKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TriggerKind) UnmarshalBinary(by []byte) error {
	newt, err := ParseTriggerKind(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for TriggerKind.
// It returns the string representation of the enum value.
func (t TriggerKind) MarshalYAML() ([]byte, error) {
	return []byte(t.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (t *TriggerKind) UnmarshalYAML(by []byte) error {
	newt, err := ParseTriggerKind(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// triggerkindNames is a constant string slice containing all enum values cononical absolute names
const triggerkindNames = "visiblehiddenfocusedtext_presentvalue_equalsurl_matchesnavigation_completesurface_stable"

// triggerkindNamesMap is a map of enum values to their canonical absolute
// name positions within the triggerkindNames string slice
var triggerkindNamesMap = map[TriggerKind]string{
	TriggerKinds.VISIBLE:            triggerkindNames[0:7],
	TriggerKinds.HIDDEN:             triggerkindNames[7:13],
	TriggerKinds.FOCUSED:            triggerkindNames[13:20],
	TriggerKinds.TEXTPRESENT:        triggerkindNames[20:32],
	TriggerKinds.VALUEEQUALS:        triggerkindNames[32:44],
	TriggerKinds.URLMATCHES:         triggerkindNames[44:55],
	TriggerKinds.NAVIGATIONCOMPLETE: triggerkindNames[55:74],
	TriggerKinds.SURFACESTABLE:      triggerkindNames[74:88],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (t TriggerKind) String() string {
	if str, ok := triggerkindNamesMap[t]; ok {
		return str
	}
	return fmt.Sprintf("triggerkind(%d)", t.triggerKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [8]struct{}
	_ = x[visible]
	_ = x[hidden-1]
	_ = x[focused-2]
	_ = x[textPresent-3]
	_ = x[valueEquals-4]
	_ = x[urlMatches-5]
	_ = x[navigationComplete-6]
	_ = x[surfaceStable-7]
}
