// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f finishreason_enum.go

package llm

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// FinishReason is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type FinishReason struct {
	finishReason
}

// finishReasonsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the FinishReason type.
type finishReasonsContainer struct {
	UNKNOWN       FinishReason
	STOP          FinishReason
	LENGTH        FinishReason
	TOOLCALLS     FinishReason
	CONTENTFILTER FinishReason
}

// FinishReasons is a main entry point using the FinishReason type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var FinishReasons = finishReasonsContainer{
	UNKNOWN: FinishReason{
		finishReason: unknown,
	},
	STOP: FinishReason{
		finishReason: stop,
	},
	LENGTH: FinishReason{
		finishReason: length,
	},
	TOOLCALLS: FinishReason{
		finishReason: toolCalls,
	},
	CONTENTFILTER: FinishReason{
		finishReason: contentFilter,
	},
}

// invalidFinishReason is an invalid sentinel value for FinishReason
var invalidFinishReason = FinishReason{
	finishReason: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (f finishReasonsContainer) allSlice() []FinishReason {
	return []FinishReason{
		FinishReasons.UNKNOWN,
		FinishReasons.STOP,
		FinishReasons.LENGTH,
		FinishReasons.TOOLCALLS,
		FinishReasons.CONTENTFILTER,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (f finishReasonsContainer) All() iter.Seq[FinishReason] {
	return func(yield func(FinishReason) bool) {
		for _, v := range f.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseFinishReason = errors.New("invalid input provided to parse to FinishReason")

// ParseFinishReason parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseFinishReason(input any) (FinishReason, error) {
	switch v := input.(type) {
	case FinishReason:
		return v, nil
	case string:
		if result := stringToFinishReason(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToFinishReason(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToFinishReason(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToFinishReason(v); result != nil {
			return *result, nil
		}
	default:
		return invalidFinishReason, fmt.Errorf("invalid type %T", input)
	}
	return invalidFinishReason, fmt.Errorf("%w: invalid value %v", ErrParseFinishReason, input)
}

// finishReasonsNameMap is a map of enum values to their FinishReason representation
// It is used to convert string representations of enum values into their FinishReason representation.
var finishReasonsNameMap = map[string]FinishReason{
	"unknown":        FinishReasons.UNKNOWN,
	"stop":           FinishReasons.STOP,
	"length":         FinishReasons.LENGTH,
	"tool_calls":     FinishReasons.TOOLCALLS,
	"content_filter": FinishReasons.CONTENTFILTER,
}

// stringToFinishReason converts a string representation of an enum value into its FinishReason representation
// It returns a pointer to the FinishReason representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToFinishReason(s string) *FinishReason {
	if t, ok := finishReasonsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToFinishReason converts a numeric value to a FinishReason
// It returns a pointer to the FinishReason representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToFinishReason[T constraints.Integer | constraints.Float](num T) *FinishReason {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(FinishReasons.allSlice()) {
		return nil
	}
	result := FinishReasons.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveFinishReasons iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveFinishReasons(f func(FinishReason)) {
	for _, p := range FinishReasons.allSlice() {
		f(p)
	}
}

// validFinishReasons is a map of enum values to their validity
var validFinishReasons = map[FinishReason]bool{
	FinishReasons.UNKNOWN:       true,
	FinishReasons.STOP:          true,
	FinishReasons.LENGTH:        true,
	FinishReasons.TOOLCALLS:     true,
	FinishReasons.CONTENTFILTER: true,
}

// IsValid checks whether the FinishReasons value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (f FinishReason) IsValid() bool {
	return validFinishReasons[f]
}

// MarshalJSON implements the json.Marshaler interface for FinishReason.
// It returns the JSON representation of the enum value as a byte slice.
func (f FinishReason) MarshalJSON() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for FinishReason.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (f *FinishReason) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newf, err := ParseFinishReason(by)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for FinishReason.
// It returns the string representation of the enum value as a byte slice
func (f FinishReason) MarshalText() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FinishReason.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (f *FinishReason) UnmarshalText(by []byte) error {
	newf, err := ParseFinishReason(by)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// Scan implements the database/sql.Scanner interface for FinishReason.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (f *FinishReason) Scan(value any) error {
	newf, err := ParseFinishReason(value)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// Value implements the database/sql/driver.Valuer interface for FinishReason.
// It returns the string representation of the enum value.
func (f FinishReason) Value() (driver.Value, error) {
	return f.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for FinishReason.
// It returns the binary representation of the enum value as a byte slice.
func (f FinishReason) MarshalBinary() ([]byte, error) {
	return []byte("\"" + f.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for FinishReason.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (f *FinishReason) UnmarshalBinary(by []byte) error {
	newf, err := ParseFinishReason(by)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for FinishReason.
// It returns the string representation of the enum value.
func (f FinishReason) MarshalYAML() ([]byte, error) {
	return []byte(f.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (f *FinishReason) UnmarshalYAML(by []byte) error {
	newf, err := ParseFinishReason(by)
	if err != nil {
		return err
	}
	*f = newf
	return nil
}

// finishreasonNames is a constant string slice containing all enum values cononical absolute names
const finishreasonNames = "unknownstoplengthtool_callscontent_filter"

// finishreasonNamesMap is a map of enum values to their canonical absolute
// name positions within the finishreasonNames string slice
var finishreasonNamesMap = map[FinishReason]string{
	FinishReasons.UNKNOWN:       finishreasonNames[0:7],
	FinishReasons.STOP:          finishreasonNames[7:11],
	FinishReasons.LENGTH:        finishreasonNames[11:17],
	FinishReasons.TOOLCALLS:     finishreasonNames[17:27],
	FinishReasons.CONTENTFILTER: finishreasonNames[27:41],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (f FinishReason) String() string {
	if str, ok := finishreasonNamesMap[f]; ok {
		return str
	}
	return fmt.Sprintf("finishreason(%d)", f.finishReason)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[unknown]
	_ = x[stop-1]
	_ = x[length-2]
	_ = x[toolCalls-3]
	_ = x[contentFilter-4]
}
