// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f reasoninghistory_enum.go

package llm

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// ReasoningHistory is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ReasoningHistory struct {
	reasoningHistory
}

// reasoningHistoriesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ReasoningHistory type.
type reasoningHistoriesContainer struct {
	INLINE ReasoningHistory
	FIELD  ReasoningHistory
	STRIP  ReasoningHistory
}

// ReasoningHistories is a main entry point using the ReasoningHistory type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ReasoningHistories = reasoningHistoriesContainer{
	INLINE: ReasoningHistory{
		reasoningHistory: inline,
	},
	FIELD: ReasoningHistory{
		reasoningHistory: field,
	},
	STRIP: ReasoningHistory{
		reasoningHistory: strip,
	},
}

// invalidReasoningHistory is an invalid sentinel value for ReasoningHistory
var invalidReasoningHistory = ReasoningHistory{
	reasoningHistory: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r reasoningHistoriesContainer) allSlice() []ReasoningHistory {
	return []ReasoningHistory{
		ReasoningHistories.INLINE,
		ReasoningHistories.FIELD,
		ReasoningHistories.STRIP,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r reasoningHistoriesContainer) All() iter.Seq[ReasoningHistory] {
	return func(yield func(ReasoningHistory) bool) {
		for _, v := range r.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseReasoningHistory = errors.New("invalid input provided to parse to ReasoningHistory")

// ParseReasoningHistory parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseReasoningHistory(input any) (ReasoningHistory, error) {
	switch v := input.(type) {
	case ReasoningHistory:
		return v, nil
	case string:
		if result := stringToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToReasoningHistory(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToReasoningHistory(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToReasoningHistory(v); result != nil {
			return *result, nil
		}
	default:
		return invalidReasoningHistory, fmt.Errorf("invalid type %T", input)
	}
	return invalidReasoningHistory, fmt.Errorf("%w: invalid value %v", ErrParseReasoningHistory, input)
}

// reasoningHistoriesNameMap is a map of enum values to their ReasoningHistory representation
// It is used to convert string representations of enum values into their ReasoningHistory representation.
var reasoningHistoriesNameMap = map[string]ReasoningHistory{
	"inline": ReasoningHistories.INLINE,
	"field":  ReasoningHistories.FIELD,
	"strip":  ReasoningHistories.STRIP,
}

// stringToReasoningHistory converts a string representation of an enum value into its ReasoningHistory representation
// It returns a pointer to the ReasoningHistory representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToReasoningHistory(s string) *ReasoningHistory {
	if t, ok := reasoningHistoriesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToReasoningHistory converts a numeric value to a ReasoningHistory
// It returns a pointer to the ReasoningHistory representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToReasoningHistory[T constraints.Integer | constraints.Float](num T) *ReasoningHistory {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ReasoningHistories.allSlice()) {
		return nil
	}
	result := ReasoningHistories.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveReasoningHistories iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveReasoningHistories(f func(ReasoningHistory)) {
	for _, p := range ReasoningHistories.allSlice() {
		f(p)
	}
}

// validReasoningHistories is a map of enum values to their validity
var validReasoningHistories = map[ReasoningHistory]bool{
	ReasoningHistories.INLINE: true,
	ReasoningHistories.FIELD:  true,
	ReasoningHistories.STRIP:  true,
}

// IsValid checks whether the ReasoningHistories value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (r ReasoningHistory) IsValid() bool {
	return validReasoningHistories[r]
}

// MarshalJSON implements the json.Marshaler interface for ReasoningHistory.
// It returns the JSON representation of the enum value as a byte slice.
func (r ReasoningHistory) MarshalJSON() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReasoningHistory.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (r *ReasoningHistory) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newr, err := ParseReasoningHistory(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ReasoningHistory.
// It returns the string representation of the enum value as a byte slice
func (r ReasoningHistory) MarshalText() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReasoningHistory.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReasoningHistory) UnmarshalText(by []byte) error {
	newr, err := ParseReasoningHistory(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Scan implements the database/sql.Scanner interface for ReasoningHistory.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (r *ReasoningHistory) Scan(value any) error {
	newr, err := ParseReasoningHistory(value)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ReasoningHistory.
// It returns the string representation of the enum value.
func (r ReasoningHistory) Value() (driver.Value, error) {
	return r.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ReasoningHistory.
// It returns the binary representation of the enum value as a byte slice.
func (r ReasoningHistory) MarshalBinary() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ReasoningHistory.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReasoningHistory) UnmarshalBinary(by []byte) error {
	newr, err := ParseReasoningHistory(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ReasoningHistory.
// It returns the string representation of the enum value.
func (r ReasoningHistory) MarshalYAML() ([]byte, error) {
	return []byte(r.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (r *ReasoningHistory) UnmarshalYAML(by []byte) error {
	newr, err := ParseReasoningHistory(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// reasoninghistoryNames is a constant string slice containing all enum values cononical absolute names
const reasoninghistoryNames = "inlinefieldstrip"

// reasoninghistoryNamesMap is a map of enum values to their canonical absolute
// name positions within the reasoninghistoryNames string slice
var reasoninghistoryNamesMap = map[ReasoningHistory]string{
	ReasoningHistories.INLINE: reasoninghistoryNames[0:6],
	ReasoningHistories.FIELD:  reasoninghistoryNames[6:11],
	ReasoningHistories.STRIP:  reasoninghistoryNames[11:16],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (r ReasoningHistory) String() string {
	if str, ok := reasoninghistoryNamesMap[r]; ok {
		return str
	}
	return fmt.Sprintf("reasoninghistory(%d)", r.reasoningHistory)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[inline]
	_ = x[field-1]
	_ = x[strip-2]
}
