// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f workspace_scope_enum.go

package tools

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// WorkspaceScopeKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type WorkspaceScopeKind struct {
	workspaceScopeKind
}

// workspaceScopeKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the WorkspaceScopeKind type.
type workspaceScopeKindsContainer struct {
	ROOT     WorkspaceScopeKind
	ARGUMENT WorkspaceScopeKind
	FIXED    WorkspaceScopeKind
	PATCH    WorkspaceScopeKind
}

// WorkspaceScopeKinds is a main entry point using the WorkspaceScopeKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var WorkspaceScopeKinds = workspaceScopeKindsContainer{
	ROOT: WorkspaceScopeKind{
		workspaceScopeKind: root,
	},
	ARGUMENT: WorkspaceScopeKind{
		workspaceScopeKind: argument,
	},
	FIXED: WorkspaceScopeKind{
		workspaceScopeKind: fixed,
	},
	PATCH: WorkspaceScopeKind{
		workspaceScopeKind: patch,
	},
}

// invalidWorkspaceScopeKind is an invalid sentinel value for WorkspaceScopeKind
var invalidWorkspaceScopeKind = WorkspaceScopeKind{
	workspaceScopeKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceScopeKindsContainer) allSlice() []WorkspaceScopeKind {
	return []WorkspaceScopeKind{
		WorkspaceScopeKinds.ROOT,
		WorkspaceScopeKinds.ARGUMENT,
		WorkspaceScopeKinds.FIXED,
		WorkspaceScopeKinds.PATCH,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceScopeKindsContainer) All() iter.Seq[WorkspaceScopeKind] {
	return func(yield func(WorkspaceScopeKind) bool) {
		for _, v := range w.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseWorkspaceScopeKind = errors.New("invalid input provided to parse to WorkspaceScopeKind")

// ParseWorkspaceScopeKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseWorkspaceScopeKind(input any) (WorkspaceScopeKind, error) {
	switch v := input.(type) {
	case WorkspaceScopeKind:
		return v, nil
	case string:
		if result := stringToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToWorkspaceScopeKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToWorkspaceScopeKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToWorkspaceScopeKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidWorkspaceScopeKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidWorkspaceScopeKind, fmt.Errorf("%w: invalid value %v", ErrParseWorkspaceScopeKind, input)
}

// workspaceScopeKindsNameMap is a map of enum values to their WorkspaceScopeKind representation
// It is used to convert string representations of enum values into their WorkspaceScopeKind representation.
var workspaceScopeKindsNameMap = map[string]WorkspaceScopeKind{
	"root":     WorkspaceScopeKinds.ROOT,
	"argument": WorkspaceScopeKinds.ARGUMENT,
	"fixed":    WorkspaceScopeKinds.FIXED,
	"patch":    WorkspaceScopeKinds.PATCH,
}

// stringToWorkspaceScopeKind converts a string representation of an enum value into its WorkspaceScopeKind representation
// It returns a pointer to the WorkspaceScopeKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToWorkspaceScopeKind(s string) *WorkspaceScopeKind {
	if t, ok := workspaceScopeKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToWorkspaceScopeKind converts a numeric value to a WorkspaceScopeKind
// It returns a pointer to the WorkspaceScopeKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToWorkspaceScopeKind[T constraints.Integer | constraints.Float](num T) *WorkspaceScopeKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(WorkspaceScopeKinds.allSlice()) {
		return nil
	}
	result := WorkspaceScopeKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveWorkspaceScopeKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveWorkspaceScopeKinds(f func(WorkspaceScopeKind)) {
	for _, p := range WorkspaceScopeKinds.allSlice() {
		f(p)
	}
}

// validWorkspaceScopeKinds is a map of enum values to their validity
var validWorkspaceScopeKinds = map[WorkspaceScopeKind]bool{
	WorkspaceScopeKinds.ROOT:     true,
	WorkspaceScopeKinds.ARGUMENT: true,
	WorkspaceScopeKinds.FIXED:    true,
	WorkspaceScopeKinds.PATCH:    true,
}

// IsValid checks whether the WorkspaceScopeKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (w WorkspaceScopeKind) IsValid() bool {
	return validWorkspaceScopeKinds[w]
}

// MarshalJSON implements the json.Marshaler interface for WorkspaceScopeKind.
// It returns the JSON representation of the enum value as a byte slice.
func (w WorkspaceScopeKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for WorkspaceScopeKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (w *WorkspaceScopeKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	neww, err := ParseWorkspaceScopeKind(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for WorkspaceScopeKind.
// It returns the string representation of the enum value as a byte slice
func (w WorkspaceScopeKind) MarshalText() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WorkspaceScopeKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceScopeKind) UnmarshalText(by []byte) error {
	neww, err := ParseWorkspaceScopeKind(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Scan implements the database/sql.Scanner interface for WorkspaceScopeKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (w *WorkspaceScopeKind) Scan(value any) error {
	neww, err := ParseWorkspaceScopeKind(value)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Value implements the database/sql/driver.Valuer interface for WorkspaceScopeKind.
// It returns the string representation of the enum value.
func (w WorkspaceScopeKind) Value() (driver.Value, error) {
	return w.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for WorkspaceScopeKind.
// It returns the binary representation of the enum value as a byte slice.
func (w WorkspaceScopeKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for WorkspaceScopeKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceScopeKind) UnmarshalBinary(by []byte) error {
	neww, err := ParseWorkspaceScopeKind(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for WorkspaceScopeKind.
// It returns the string representation of the enum value.
func (w WorkspaceScopeKind) MarshalYAML() ([]byte, error) {
	return []byte(w.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (w *WorkspaceScopeKind) UnmarshalYAML(by []byte) error {
	neww, err := ParseWorkspaceScopeKind(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// workspacescopekindNames is a constant string slice containing all enum values cononical absolute names
const workspacescopekindNames = "rootargumentfixedpatch"

// workspacescopekindNamesMap is a map of enum values to their canonical absolute
// name positions within the workspacescopekindNames string slice
var workspacescopekindNamesMap = map[WorkspaceScopeKind]string{
	WorkspaceScopeKinds.ROOT:     workspacescopekindNames[0:4],
	WorkspaceScopeKinds.ARGUMENT: workspacescopekindNames[4:12],
	WorkspaceScopeKinds.FIXED:    workspacescopekindNames[12:17],
	WorkspaceScopeKinds.PATCH:    workspacescopekindNames[17:22],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (w WorkspaceScopeKind) String() string {
	if str, ok := workspacescopekindNamesMap[w]; ok {
		return str
	}
	return fmt.Sprintf("workspacescopekind(%d)", w.workspaceScopeKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[root]
	_ = x[argument-1]
	_ = x[fixed-2]
	_ = x[patch-3]
}
