// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f workspace_access_enum.go

package tools

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// WorkspaceAccess is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type WorkspaceAccess struct {
	workspaceAccess
}

// workspaceAccessesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the WorkspaceAccess type.
type workspaceAccessesContainer struct {
	INVALID WorkspaceAccess
	NONE    WorkspaceAccess
	READ    WorkspaceAccess
	WRITE   WorkspaceAccess
}

// WorkspaceAccesses is a main entry point using the WorkspaceAccess type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var WorkspaceAccesses = workspaceAccessesContainer{
	INVALID: WorkspaceAccess{
		workspaceAccess: invalid,
	},
	NONE: WorkspaceAccess{
		workspaceAccess: none,
	},
	READ: WorkspaceAccess{
		workspaceAccess: read,
	},
	WRITE: WorkspaceAccess{
		workspaceAccess: write,
	},
}

// invalidWorkspaceAccess is an invalid sentinel value for WorkspaceAccess
var invalidWorkspaceAccess = WorkspaceAccess{
	workspaceAccess: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceAccessesContainer) allSlice() []WorkspaceAccess {
	return []WorkspaceAccess{
		WorkspaceAccesses.NONE,
		WorkspaceAccesses.READ,
		WorkspaceAccesses.WRITE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceAccessesContainer) All() iter.Seq[WorkspaceAccess] {
	return func(yield func(WorkspaceAccess) bool) {
		for _, v := range w.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseWorkspaceAccess = errors.New("invalid input provided to parse to WorkspaceAccess")

// ParseWorkspaceAccess parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseWorkspaceAccess(input any) (WorkspaceAccess, error) {
	switch v := input.(type) {
	case WorkspaceAccess:
		return v, nil
	case string:
		if result := stringToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToWorkspaceAccess(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToWorkspaceAccess(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToWorkspaceAccess(v); result != nil {
			return *result, nil
		}
	default:
		return invalidWorkspaceAccess, fmt.Errorf("invalid type %T", input)
	}
	return invalidWorkspaceAccess, fmt.Errorf("%w: invalid value %v", ErrParseWorkspaceAccess, input)
}

// workspaceAccessesNameMap is a map of enum values to their WorkspaceAccess representation
// It is used to convert string representations of enum values into their WorkspaceAccess representation.
var workspaceAccessesNameMap = map[string]WorkspaceAccess{
	"invalid": WorkspaceAccesses.INVALID,
	"none":    WorkspaceAccesses.NONE,
	"read":    WorkspaceAccesses.READ,
	"write":   WorkspaceAccesses.WRITE,
}

// stringToWorkspaceAccess converts a string representation of an enum value into its WorkspaceAccess representation
// It returns a pointer to the WorkspaceAccess representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToWorkspaceAccess(s string) *WorkspaceAccess {
	if t, ok := workspaceAccessesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToWorkspaceAccess converts a numeric value to a WorkspaceAccess
// It returns a pointer to the WorkspaceAccess representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToWorkspaceAccess[T constraints.Integer | constraints.Float](num T) *WorkspaceAccess {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(WorkspaceAccesses.allSlice()) {
		return nil
	}
	result := WorkspaceAccesses.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveWorkspaceAccesses iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveWorkspaceAccesses(f func(WorkspaceAccess)) {
	for _, p := range WorkspaceAccesses.allSlice() {
		f(p)
	}
}

// validWorkspaceAccesses is a map of enum values to their validity
var validWorkspaceAccesses = map[WorkspaceAccess]bool{
	WorkspaceAccesses.INVALID: false,
	WorkspaceAccesses.NONE:    true,
	WorkspaceAccesses.READ:    true,
	WorkspaceAccesses.WRITE:   true,
}

// IsValid checks whether the WorkspaceAccesses value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (w WorkspaceAccess) IsValid() bool {
	return validWorkspaceAccesses[w]
}

// MarshalJSON implements the json.Marshaler interface for WorkspaceAccess.
// It returns the JSON representation of the enum value as a byte slice.
func (w WorkspaceAccess) MarshalJSON() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for WorkspaceAccess.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (w *WorkspaceAccess) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	neww, err := ParseWorkspaceAccess(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for WorkspaceAccess.
// It returns the string representation of the enum value as a byte slice
func (w WorkspaceAccess) MarshalText() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WorkspaceAccess.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceAccess) UnmarshalText(by []byte) error {
	neww, err := ParseWorkspaceAccess(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Scan implements the database/sql.Scanner interface for WorkspaceAccess.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (w *WorkspaceAccess) Scan(value any) error {
	neww, err := ParseWorkspaceAccess(value)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Value implements the database/sql/driver.Valuer interface for WorkspaceAccess.
// It returns the string representation of the enum value.
func (w WorkspaceAccess) Value() (driver.Value, error) {
	return w.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for WorkspaceAccess.
// It returns the binary representation of the enum value as a byte slice.
func (w WorkspaceAccess) MarshalBinary() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for WorkspaceAccess.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceAccess) UnmarshalBinary(by []byte) error {
	neww, err := ParseWorkspaceAccess(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for WorkspaceAccess.
// It returns the string representation of the enum value.
func (w WorkspaceAccess) MarshalYAML() ([]byte, error) {
	return []byte(w.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (w *WorkspaceAccess) UnmarshalYAML(by []byte) error {
	neww, err := ParseWorkspaceAccess(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// workspaceaccessNames is a constant string slice containing all enum values cononical absolute names
const workspaceaccessNames = "invalidnonereadwrite"

// workspaceaccessNamesMap is a map of enum values to their canonical absolute
// name positions within the workspaceaccessNames string slice
var workspaceaccessNamesMap = map[WorkspaceAccess]string{
	WorkspaceAccesses.INVALID: workspaceaccessNames[0:7],
	WorkspaceAccesses.NONE:    workspaceaccessNames[7:11],
	WorkspaceAccesses.READ:    workspaceaccessNames[11:15],
	WorkspaceAccesses.WRITE:   workspaceaccessNames[15:20],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (w WorkspaceAccess) String() string {
	if str, ok := workspaceaccessNamesMap[w]; ok {
		return str
	}
	return fmt.Sprintf("workspaceaccess(%d)", w.workspaceAccess)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[invalid]
	_ = x[none-1]
	_ = x[read-2]
	_ = x[write-3]
}
