// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f workspace_wait_outcome_enum.go

package tools

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// WorkspaceWaitOutcome is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type WorkspaceWaitOutcome struct {
	workspaceWaitOutcome
}

// workspaceWaitOutcomesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the WorkspaceWaitOutcome type.
type workspaceWaitOutcomesContainer struct {
	WORKSPACEWAITACQUIRED  WorkspaceWaitOutcome
	WORKSPACEWAITCANCELLED WorkspaceWaitOutcome
}

// WorkspaceWaitOutcomes is a main entry point using the WorkspaceWaitOutcome type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var WorkspaceWaitOutcomes = workspaceWaitOutcomesContainer{
	WORKSPACEWAITACQUIRED: WorkspaceWaitOutcome{
		workspaceWaitOutcome: workspaceWaitAcquired,
	},
	WORKSPACEWAITCANCELLED: WorkspaceWaitOutcome{
		workspaceWaitOutcome: workspaceWaitCancelled,
	},
}

// invalidWorkspaceWaitOutcome is an invalid sentinel value for WorkspaceWaitOutcome
var invalidWorkspaceWaitOutcome = WorkspaceWaitOutcome{
	workspaceWaitOutcome: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceWaitOutcomesContainer) allSlice() []WorkspaceWaitOutcome {
	return []WorkspaceWaitOutcome{
		WorkspaceWaitOutcomes.WORKSPACEWAITACQUIRED,
		WorkspaceWaitOutcomes.WORKSPACEWAITCANCELLED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workspaceWaitOutcomesContainer) All() iter.Seq[WorkspaceWaitOutcome] {
	return func(yield func(WorkspaceWaitOutcome) bool) {
		for _, v := range w.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseWorkspaceWaitOutcome = errors.New("invalid input provided to parse to WorkspaceWaitOutcome")

// ParseWorkspaceWaitOutcome parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseWorkspaceWaitOutcome(input any) (WorkspaceWaitOutcome, error) {
	switch v := input.(type) {
	case WorkspaceWaitOutcome:
		return v, nil
	case string:
		if result := stringToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToWorkspaceWaitOutcome(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToWorkspaceWaitOutcome(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToWorkspaceWaitOutcome(v); result != nil {
			return *result, nil
		}
	default:
		return invalidWorkspaceWaitOutcome, fmt.Errorf("invalid type %T", input)
	}
	return invalidWorkspaceWaitOutcome, fmt.Errorf("%w: invalid value %v", ErrParseWorkspaceWaitOutcome, input)
}

// workspaceWaitOutcomesNameMap is a map of enum values to their WorkspaceWaitOutcome representation
// It is used to convert string representations of enum values into their WorkspaceWaitOutcome representation.
var workspaceWaitOutcomesNameMap = map[string]WorkspaceWaitOutcome{
	"acquired":  WorkspaceWaitOutcomes.WORKSPACEWAITACQUIRED,
	"cancelled": WorkspaceWaitOutcomes.WORKSPACEWAITCANCELLED,
}

// stringToWorkspaceWaitOutcome converts a string representation of an enum value into its WorkspaceWaitOutcome representation
// It returns a pointer to the WorkspaceWaitOutcome representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToWorkspaceWaitOutcome(s string) *WorkspaceWaitOutcome {
	if t, ok := workspaceWaitOutcomesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToWorkspaceWaitOutcome converts a numeric value to a WorkspaceWaitOutcome
// It returns a pointer to the WorkspaceWaitOutcome representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToWorkspaceWaitOutcome[T constraints.Integer | constraints.Float](num T) *WorkspaceWaitOutcome {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(WorkspaceWaitOutcomes.allSlice()) {
		return nil
	}
	result := WorkspaceWaitOutcomes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveWorkspaceWaitOutcomes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveWorkspaceWaitOutcomes(f func(WorkspaceWaitOutcome)) {
	for _, p := range WorkspaceWaitOutcomes.allSlice() {
		f(p)
	}
}

// validWorkspaceWaitOutcomes is a map of enum values to their validity
var validWorkspaceWaitOutcomes = map[WorkspaceWaitOutcome]bool{
	WorkspaceWaitOutcomes.WORKSPACEWAITACQUIRED:  true,
	WorkspaceWaitOutcomes.WORKSPACEWAITCANCELLED: true,
}

// IsValid checks whether the WorkspaceWaitOutcomes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (w WorkspaceWaitOutcome) IsValid() bool {
	return validWorkspaceWaitOutcomes[w]
}

// MarshalJSON implements the json.Marshaler interface for WorkspaceWaitOutcome.
// It returns the JSON representation of the enum value as a byte slice.
func (w WorkspaceWaitOutcome) MarshalJSON() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for WorkspaceWaitOutcome.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (w *WorkspaceWaitOutcome) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	neww, err := ParseWorkspaceWaitOutcome(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for WorkspaceWaitOutcome.
// It returns the string representation of the enum value as a byte slice
func (w WorkspaceWaitOutcome) MarshalText() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WorkspaceWaitOutcome.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceWaitOutcome) UnmarshalText(by []byte) error {
	neww, err := ParseWorkspaceWaitOutcome(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Scan implements the database/sql.Scanner interface for WorkspaceWaitOutcome.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (w *WorkspaceWaitOutcome) Scan(value any) error {
	neww, err := ParseWorkspaceWaitOutcome(value)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Value implements the database/sql/driver.Valuer interface for WorkspaceWaitOutcome.
// It returns the string representation of the enum value.
func (w WorkspaceWaitOutcome) Value() (driver.Value, error) {
	return w.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for WorkspaceWaitOutcome.
// It returns the binary representation of the enum value as a byte slice.
func (w WorkspaceWaitOutcome) MarshalBinary() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for WorkspaceWaitOutcome.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkspaceWaitOutcome) UnmarshalBinary(by []byte) error {
	neww, err := ParseWorkspaceWaitOutcome(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for WorkspaceWaitOutcome.
// It returns the string representation of the enum value.
func (w WorkspaceWaitOutcome) MarshalYAML() ([]byte, error) {
	return []byte(w.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (w *WorkspaceWaitOutcome) UnmarshalYAML(by []byte) error {
	neww, err := ParseWorkspaceWaitOutcome(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// workspacewaitoutcomeNames is a constant string slice containing all enum values cononical absolute names
const workspacewaitoutcomeNames = "acquiredcancelled"

// workspacewaitoutcomeNamesMap is a map of enum values to their canonical absolute
// name positions within the workspacewaitoutcomeNames string slice
var workspacewaitoutcomeNamesMap = map[WorkspaceWaitOutcome]string{
	WorkspaceWaitOutcomes.WORKSPACEWAITACQUIRED:  workspacewaitoutcomeNames[0:8],
	WorkspaceWaitOutcomes.WORKSPACEWAITCANCELLED: workspacewaitoutcomeNames[8:17],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (w WorkspaceWaitOutcome) String() string {
	if str, ok := workspacewaitoutcomeNamesMap[w]; ok {
		return str
	}
	return fmt.Sprintf("workspacewaitoutcome(%d)", w.workspaceWaitOutcome)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[workspaceWaitAcquired]
	_ = x[workspaceWaitCancelled-1]
}
