package code

import (
	"fmt"
	"regexp"
	"strings"
)

const generatedHeaderMaxBytes = 2048

var generatedGoMarker = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT\.$`)
var goenumsSourceFlag = regexp.MustCompile(`(?m)^// goenums -f ([^\s]+)$`)

type generatedFileInfo struct {
	Generator string
	Source    string
}

func detectGeneratedFile(data []byte) (generatedFileInfo, bool) {
	header := data
	if len(header) > generatedHeaderMaxBytes {
		header = header[:generatedHeaderMaxBytes]
	}
	marker := generatedGoMarker.Find(header)
	if marker == nil {
		return generatedFileInfo{}, false
	}
	info := generatedFileInfo{}
	line := strings.TrimSpace(string(marker))
	line = strings.TrimPrefix(line, "// Code generated by ")
	line = strings.TrimSuffix(line, "; DO NOT EDIT.")
	line = strings.TrimSuffix(line, ". DO NOT EDIT.")
	info.Generator = strings.TrimSpace(line)
	if match := goenumsSourceFlag.FindSubmatch(header); len(match) == 2 {
		info.Source = string(match[1])
	}
	return info, true
}

func generatedFileNotice(info generatedFileInfo) string {
	var b strings.Builder
	b.WriteString("generated file — do not edit directly")
	if info.Generator != "" {
		fmt.Fprintf(&b, " (generator: %s)", info.Generator)
	}
	if info.Source != "" {
		fmt.Fprintf(&b, "; edit source `%s` and regenerate", info.Source)
	}
	return b.String()
}

func appendGeneratedFileNotice(body string, data []byte) string {
	info, generated := detectGeneratedFile(data)
	if !generated {
		return body
	}
	if body != "" && !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return body + "\n... (" + generatedFileNotice(info) + ")\n"
}

func generatedEditError(path string, data []byte) error {
	info, generated := detectGeneratedFile(data)
	if !generated {
		return nil
	}
	return fmt.Errorf("%q: %s", path, generatedFileNotice(info))
}
