package code

// StepStatus marks where a plan step is in its lifecycle — three states
// mirroring Codex's update_plan API. The type, its String()/JSON wire
// form ("pending" / "in_progress" / "completed"), and ParseStepStatus
// (which also accepts the "in-progress" / "inprogress" / "done" aliases)
// are generated by goenums from step_status.go. Callers normalise case
// and surrounding whitespace before parsing (see update_plan).

// PlanStep is one entry in the ordered plan. Text is the
// human-readable description; Status is the lifecycle marker. Steps
// have no stable identity beyond their position — update_plan
// replaces the whole list, so callers don't need to thread IDs.
type PlanStep struct {
	Text   string     `json:"step"`
	Status StepStatus `json:"status"`
}

// Plan is the structured state mutated by update_plan and rendered
// in the plan dock tab. Explanation is the optional one-liner the
// model sends with each update (e.g. "split step 2 into two steps")
// — surfaced in the pane so the user can see why the plan changed.
type Plan struct {
	Steps       []PlanStep `json:"steps"`
	Explanation string     `json:"explanation,omitempty"`
}

// IsEmpty reports whether the plan has any steps. Used by the pane
// to decide between rendering the empty placeholder and the list.
func (p Plan) IsEmpty() bool { return len(p.Steps) == 0 }

// PlanStore is the dependency seam between the update_plan tool and
// whatever process-wide state owns the live plan. Tools are wired in
// at registration with a concrete *shellModel implementation; tests
// use an in-memory fake.
//
// Defined consumer-side here (not in zkit/agent/runner or zarlcode/tui)
// because the tool is the only direct caller. Other consumers read
// state via the same interface from wherever they happen to live.
type PlanStore interface {
	// SetPlan replaces the current plan with p. The store is expected
	// to broadcast the change to any listeners (typically the TUI)
	// before returning, so the user sees the new state immediately
	// after the tool call completes.
	SetPlan(p Plan)
	// GetPlan returns the current plan (zero-value Plan when none).
	GetPlan() Plan
}

// memoryPlanStore is the simplest possible PlanStore — useful for
// tests and for the smoke shell that doesn't bring up a TUI. The
// tool gets the same semantics in tests as in production, and the
// production wiring just adds a tea.Msg broadcast on top.
type memoryPlanStore struct {
	plan Plan
}

// NewMemoryPlanStore returns a PlanStore backed by an in-memory value.
// No locking — the runner serialises tool calls so concurrent SetPlan
// from multiple tool invocations can't happen.
func NewMemoryPlanStore() *memoryPlanStore { return &memoryPlanStore{} }

func (m *memoryPlanStore) SetPlan(p Plan) { m.plan = p }
func (m *memoryPlanStore) GetPlan() Plan  { return m.plan }
