// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f step_status.go

package code

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// StepStatus is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type StepStatus struct {
	stepStatus
}

// stepStatusesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the StepStatus type.
type stepStatusesContainer struct {
	PENDING    StepStatus
	INPROGRESS StepStatus
	COMPLETED  StepStatus
}

// StepStatuses is a main entry point using the StepStatus type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var StepStatuses = stepStatusesContainer{
	PENDING: StepStatus{
		stepStatus: pending,
	},
	INPROGRESS: StepStatus{
		stepStatus: inProgress,
	},
	COMPLETED: StepStatus{
		stepStatus: completed,
	},
}

// invalidStepStatus is an invalid sentinel value for StepStatus
var invalidStepStatus = StepStatus{
	stepStatus: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s stepStatusesContainer) allSlice() []StepStatus {
	return []StepStatus{
		StepStatuses.PENDING,
		StepStatuses.INPROGRESS,
		StepStatuses.COMPLETED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s stepStatusesContainer) All() iter.Seq[StepStatus] {
	return func(yield func(StepStatus) bool) {
		for _, v := range s.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseStepStatus = errors.New("invalid input provided to parse to StepStatus")

// ParseStepStatus parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseStepStatus(input any) (StepStatus, error) {
	switch v := input.(type) {
	case StepStatus:
		return v, nil
	case string:
		if result := stringToStepStatus(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToStepStatus(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToStepStatus(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToStepStatus(v); result != nil {
			return *result, nil
		}
	default:
		return invalidStepStatus, fmt.Errorf("invalid type %T", input)
	}
	return invalidStepStatus, fmt.Errorf("%w: invalid value %v", ErrParseStepStatus, input)
}

// stepStatusesNameMap is a map of enum values to their StepStatus representation
// It is used to convert string representations of enum values into their StepStatus representation.
var stepStatusesNameMap = map[string]StepStatus{
	"pending":     StepStatuses.PENDING,
	"in_progress": StepStatuses.INPROGRESS,
	"in-progress": StepStatuses.INPROGRESS,
	"inprogress":  StepStatuses.INPROGRESS,
	"completed":   StepStatuses.COMPLETED,
	"done":        StepStatuses.COMPLETED,
}

// stringToStepStatus converts a string representation of an enum value into its StepStatus representation
// It returns a pointer to the StepStatus representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToStepStatus(s string) *StepStatus {
	if t, ok := stepStatusesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToStepStatus converts a numeric value to a StepStatus
// It returns a pointer to the StepStatus representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToStepStatus[T constraints.Integer | constraints.Float](num T) *StepStatus {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(StepStatuses.allSlice()) {
		return nil
	}
	result := StepStatuses.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveStepStatuses iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveStepStatuses(f func(StepStatus)) {
	for _, p := range StepStatuses.allSlice() {
		f(p)
	}
}

// validStepStatuses is a map of enum values to their validity
var validStepStatuses = map[StepStatus]bool{
	StepStatuses.PENDING:    true,
	StepStatuses.INPROGRESS: true,
	StepStatuses.COMPLETED:  true,
}

// IsValid checks whether the StepStatuses value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (s StepStatus) IsValid() bool {
	return validStepStatuses[s]
}

// MarshalJSON implements the json.Marshaler interface for StepStatus.
// It returns the JSON representation of the enum value as a byte slice.
func (s StepStatus) MarshalJSON() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for StepStatus.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (s *StepStatus) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	news, err := ParseStepStatus(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for StepStatus.
// It returns the string representation of the enum value as a byte slice
func (s StepStatus) MarshalText() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for StepStatus.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *StepStatus) UnmarshalText(by []byte) error {
	news, err := ParseStepStatus(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Scan implements the database/sql.Scanner interface for StepStatus.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (s *StepStatus) Scan(value any) error {
	news, err := ParseStepStatus(value)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Value implements the database/sql/driver.Valuer interface for StepStatus.
// It returns the string representation of the enum value.
func (s StepStatus) Value() (driver.Value, error) {
	return s.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for StepStatus.
// It returns the binary representation of the enum value as a byte slice.
func (s StepStatus) MarshalBinary() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for StepStatus.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *StepStatus) UnmarshalBinary(by []byte) error {
	news, err := ParseStepStatus(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for StepStatus.
// It returns the string representation of the enum value.
func (s StepStatus) MarshalYAML() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (s *StepStatus) UnmarshalYAML(by []byte) error {
	news, err := ParseStepStatus(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// stepstatusNames is a constant string slice containing all enum values cononical absolute names
const stepstatusNames = "pendingin_progresscompleted"

// stepstatusNamesMap is a map of enum values to their canonical absolute
// name positions within the stepstatusNames string slice
var stepstatusNamesMap = map[StepStatus]string{
	StepStatuses.PENDING:    stepstatusNames[0:7],
	StepStatuses.INPROGRESS: stepstatusNames[7:18],
	StepStatuses.COMPLETED:  stepstatusNames[18:27],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (s StepStatus) String() string {
	if str, ok := stepstatusNamesMap[s]; ok {
		return str
	}
	return fmt.Sprintf("stepstatus(%d)", s.stepStatus)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[pending]
	_ = x[inProgress-1]
	_ = x[completed-2]
}
