// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f distance_enum.go

package qdrant

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// Distance is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type Distance struct {
	distance
}

// distancesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the Distance type.
type distancesContainer struct {
	COSINE    Distance
	DOT       Distance
	EUCLID    Distance
	MANHATTAN Distance
}

// Distances is a main entry point using the Distance type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Distances = distancesContainer{
	COSINE: Distance{
		distance: cosine,
	},
	DOT: Distance{
		distance: dot,
	},
	EUCLID: Distance{
		distance: euclid,
	},
	MANHATTAN: Distance{
		distance: manhattan,
	},
}

// invalidDistance is an invalid sentinel value for Distance
var invalidDistance = Distance{
	distance: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (d distancesContainer) allSlice() []Distance {
	return []Distance{
		Distances.COSINE,
		Distances.DOT,
		Distances.EUCLID,
		Distances.MANHATTAN,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (d distancesContainer) All() iter.Seq[Distance] {
	return func(yield func(Distance) bool) {
		for _, v := range d.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseDistance = errors.New("invalid input provided to parse to Distance")

// ParseDistance parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseDistance(input any) (Distance, error) {
	switch v := input.(type) {
	case Distance:
		return v, nil
	case string:
		if result := stringToDistance(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToDistance(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToDistance(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToDistance(v); result != nil {
			return *result, nil
		}
	default:
		return invalidDistance, fmt.Errorf("invalid type %T", input)
	}
	return invalidDistance, fmt.Errorf("%w: invalid value %v", ErrParseDistance, input)
}

// distancesNameMap is a map of enum values to their Distance representation
// It is used to convert string representations of enum values into their Distance representation.
var distancesNameMap = map[string]Distance{
	"Cosine":    Distances.COSINE,
	"Dot":       Distances.DOT,
	"Euclid":    Distances.EUCLID,
	"Manhattan": Distances.MANHATTAN,
}

// stringToDistance converts a string representation of an enum value into its Distance representation
// It returns a pointer to the Distance representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToDistance(s string) *Distance {
	if t, ok := distancesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToDistance converts a numeric value to a Distance
// It returns a pointer to the Distance representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToDistance[T constraints.Integer | constraints.Float](num T) *Distance {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(Distances.allSlice()) {
		return nil
	}
	result := Distances.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveDistances iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveDistances(f func(Distance)) {
	for _, p := range Distances.allSlice() {
		f(p)
	}
}

// validDistances is a map of enum values to their validity
var validDistances = map[Distance]bool{
	Distances.COSINE:    true,
	Distances.DOT:       true,
	Distances.EUCLID:    true,
	Distances.MANHATTAN: true,
}

// IsValid checks whether the Distances value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (d Distance) IsValid() bool {
	return validDistances[d]
}

// MarshalJSON implements the json.Marshaler interface for Distance.
// It returns the JSON representation of the enum value as a byte slice.
func (d Distance) MarshalJSON() ([]byte, error) {
	return []byte("\"" + d.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Distance.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (d *Distance) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newd, err := ParseDistance(by)
	if err != nil {
		return err
	}
	*d = newd
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Distance.
// It returns the string representation of the enum value as a byte slice
func (d Distance) MarshalText() ([]byte, error) {
	return []byte("\"" + d.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Distance.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (d *Distance) UnmarshalText(by []byte) error {
	newd, err := ParseDistance(by)
	if err != nil {
		return err
	}
	*d = newd
	return nil
}

// Scan implements the database/sql.Scanner interface for Distance.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (d *Distance) Scan(value any) error {
	newd, err := ParseDistance(value)
	if err != nil {
		return err
	}
	*d = newd
	return nil
}

// Value implements the database/sql/driver.Valuer interface for Distance.
// It returns the string representation of the enum value.
func (d Distance) Value() (driver.Value, error) {
	return d.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Distance.
// It returns the binary representation of the enum value as a byte slice.
func (d Distance) MarshalBinary() ([]byte, error) {
	return []byte("\"" + d.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Distance.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (d *Distance) UnmarshalBinary(by []byte) error {
	newd, err := ParseDistance(by)
	if err != nil {
		return err
	}
	*d = newd
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for Distance.
// It returns the string representation of the enum value.
func (d Distance) MarshalYAML() ([]byte, error) {
	return []byte(d.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (d *Distance) UnmarshalYAML(by []byte) error {
	newd, err := ParseDistance(by)
	if err != nil {
		return err
	}
	*d = newd
	return nil
}

// distanceNames is a constant string slice containing all enum values cononical absolute names
const distanceNames = "CosineDotEuclidManhattan"

// distanceNamesMap is a map of enum values to their canonical absolute
// name positions within the distanceNames string slice
var distanceNamesMap = map[Distance]string{
	Distances.COSINE:    distanceNames[0:6],
	Distances.DOT:       distanceNames[6:9],
	Distances.EUCLID:    distanceNames[9:15],
	Distances.MANHATTAN: distanceNames[15:24],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (d Distance) String() string {
	if str, ok := distanceNamesMap[d]; ok {
		return str
	}
	return fmt.Sprintf("distance(%d)", d.distance)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[cosine]
	_ = x[dot-1]
	_ = x[euclid-2]
	_ = x[manhattan-3]
}
