// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f workmode_enum.go

package taskscope

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// WorkMode is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type WorkMode struct {
	workMode
}

// workModesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the WorkMode type.
type workModesContainer struct {
	NONE      WorkMode
	EXPLORE   WorkMode
	VERIFY    WorkMode
	IMPLEMENT WorkMode
}

// WorkModes is a main entry point using the WorkMode type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var WorkModes = workModesContainer{
	NONE: WorkMode{
		workMode: none,
	},
	EXPLORE: WorkMode{
		workMode: explore,
	},
	VERIFY: WorkMode{
		workMode: verify,
	},
	IMPLEMENT: WorkMode{
		workMode: implement,
	},
}

// invalidWorkMode is an invalid sentinel value for WorkMode
var invalidWorkMode = WorkMode{
	workMode: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workModesContainer) allSlice() []WorkMode {
	return []WorkMode{
		WorkModes.EXPLORE,
		WorkModes.VERIFY,
		WorkModes.IMPLEMENT,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (w workModesContainer) All() iter.Seq[WorkMode] {
	return func(yield func(WorkMode) bool) {
		for _, v := range w.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseWorkMode = errors.New("invalid input provided to parse to WorkMode")

// ParseWorkMode parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseWorkMode(input any) (WorkMode, error) {
	switch v := input.(type) {
	case WorkMode:
		return v, nil
	case string:
		if result := stringToWorkMode(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToWorkMode(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToWorkMode(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToWorkMode(v); result != nil {
			return *result, nil
		}
	default:
		return invalidWorkMode, fmt.Errorf("invalid type %T", input)
	}
	return invalidWorkMode, fmt.Errorf("%w: invalid value %v", ErrParseWorkMode, input)
}

// workModesNameMap is a map of enum values to their WorkMode representation
// It is used to convert string representations of enum values into their WorkMode representation.
var workModesNameMap = map[string]WorkMode{
	"none":      WorkModes.NONE,
	"explore":   WorkModes.EXPLORE,
	"verify":    WorkModes.VERIFY,
	"implement": WorkModes.IMPLEMENT,
}

// stringToWorkMode converts a string representation of an enum value into its WorkMode representation
// It returns a pointer to the WorkMode representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToWorkMode(s string) *WorkMode {
	if t, ok := workModesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToWorkMode converts a numeric value to a WorkMode
// It returns a pointer to the WorkMode representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToWorkMode[T constraints.Integer | constraints.Float](num T) *WorkMode {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(WorkModes.allSlice()) {
		return nil
	}
	result := WorkModes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveWorkModes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveWorkModes(f func(WorkMode)) {
	for _, p := range WorkModes.allSlice() {
		f(p)
	}
}

// validWorkModes is a map of enum values to their validity
var validWorkModes = map[WorkMode]bool{
	WorkModes.NONE:      false,
	WorkModes.EXPLORE:   true,
	WorkModes.VERIFY:    true,
	WorkModes.IMPLEMENT: true,
}

// IsValid checks whether the WorkModes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (w WorkMode) IsValid() bool {
	return validWorkModes[w]
}

// MarshalJSON implements the json.Marshaler interface for WorkMode.
// It returns the JSON representation of the enum value as a byte slice.
func (w WorkMode) MarshalJSON() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for WorkMode.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (w *WorkMode) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	neww, err := ParseWorkMode(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for WorkMode.
// It returns the string representation of the enum value as a byte slice
func (w WorkMode) MarshalText() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for WorkMode.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkMode) UnmarshalText(by []byte) error {
	neww, err := ParseWorkMode(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Scan implements the database/sql.Scanner interface for WorkMode.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (w *WorkMode) Scan(value any) error {
	neww, err := ParseWorkMode(value)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// Value implements the database/sql/driver.Valuer interface for WorkMode.
// It returns the string representation of the enum value.
func (w WorkMode) Value() (driver.Value, error) {
	return w.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for WorkMode.
// It returns the binary representation of the enum value as a byte slice.
func (w WorkMode) MarshalBinary() ([]byte, error) {
	return []byte("\"" + w.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for WorkMode.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (w *WorkMode) UnmarshalBinary(by []byte) error {
	neww, err := ParseWorkMode(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for WorkMode.
// It returns the string representation of the enum value.
func (w WorkMode) MarshalYAML() ([]byte, error) {
	return []byte(w.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (w *WorkMode) UnmarshalYAML(by []byte) error {
	neww, err := ParseWorkMode(by)
	if err != nil {
		return err
	}
	*w = neww
	return nil
}

// workmodeNames is a constant string slice containing all enum values cononical absolute names
const workmodeNames = "noneexploreverifyimplement"

// workmodeNamesMap is a map of enum values to their canonical absolute
// name positions within the workmodeNames string slice
var workmodeNamesMap = map[WorkMode]string{
	WorkModes.NONE:      workmodeNames[0:4],
	WorkModes.EXPLORE:   workmodeNames[4:11],
	WorkModes.VERIFY:    workmodeNames[11:17],
	WorkModes.IMPLEMENT: workmodeNames[17:26],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (w WorkMode) String() string {
	if str, ok := workmodeNamesMap[w]; ok {
		return str
	}
	return fmt.Sprintf("workmode(%d)", w.workMode)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[none]
	_ = x[explore-1]
	_ = x[verify-2]
	_ = x[implement-3]
}
