// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f prompt_profile.go

package engine

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// PromptProfile is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type PromptProfile struct {
	promptProfile
}

// promptProfilesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the PromptProfile type.
type promptProfilesContainer struct {
	INVALID  PromptProfile
	STANDARD PromptProfile
	LEAN     PromptProfile
}

// PromptProfiles is a main entry point using the PromptProfile type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var PromptProfiles = promptProfilesContainer{
	INVALID: PromptProfile{
		promptProfile: invalid,
	},
	STANDARD: PromptProfile{
		promptProfile: standard,
	},
	LEAN: PromptProfile{
		promptProfile: lean,
	},
}

// invalidPromptProfile is an invalid sentinel value for PromptProfile
var invalidPromptProfile = PromptProfile{
	promptProfile: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (p promptProfilesContainer) allSlice() []PromptProfile {
	return []PromptProfile{
		PromptProfiles.STANDARD,
		PromptProfiles.LEAN,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (p promptProfilesContainer) All() iter.Seq[PromptProfile] {
	return func(yield func(PromptProfile) bool) {
		for _, v := range p.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParsePromptProfile = errors.New("invalid input provided to parse to PromptProfile")

// ParsePromptProfile parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParsePromptProfile(input any) (PromptProfile, error) {
	switch v := input.(type) {
	case PromptProfile:
		return v, nil
	case string:
		if result := stringToPromptProfile(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToPromptProfile(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToPromptProfile(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToPromptProfile(v); result != nil {
			return *result, nil
		}
	default:
		return invalidPromptProfile, fmt.Errorf("invalid type %T", input)
	}
	return invalidPromptProfile, fmt.Errorf("%w: invalid value %v", ErrParsePromptProfile, input)
}

// promptProfilesNameMap is a map of enum values to their PromptProfile representation
// It is used to convert string representations of enum values into their PromptProfile representation.
var promptProfilesNameMap = map[string]PromptProfile{
	"invalid":  PromptProfiles.INVALID,
	"standard": PromptProfiles.STANDARD,
	"compact":  PromptProfiles.LEAN,
}

// stringToPromptProfile converts a string representation of an enum value into its PromptProfile representation
// It returns a pointer to the PromptProfile representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToPromptProfile(s string) *PromptProfile {
	if t, ok := promptProfilesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToPromptProfile converts a numeric value to a PromptProfile
// It returns a pointer to the PromptProfile representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToPromptProfile[T constraints.Integer | constraints.Float](num T) *PromptProfile {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(PromptProfiles.allSlice()) {
		return nil
	}
	result := PromptProfiles.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustivePromptProfiles iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustivePromptProfiles(f func(PromptProfile)) {
	for _, p := range PromptProfiles.allSlice() {
		f(p)
	}
}

// validPromptProfiles is a map of enum values to their validity
var validPromptProfiles = map[PromptProfile]bool{
	PromptProfiles.INVALID:  false,
	PromptProfiles.STANDARD: true,
	PromptProfiles.LEAN:     true,
}

// IsValid checks whether the PromptProfiles value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (p PromptProfile) IsValid() bool {
	return validPromptProfiles[p]
}

// MarshalJSON implements the json.Marshaler interface for PromptProfile.
// It returns the JSON representation of the enum value as a byte slice.
func (p PromptProfile) MarshalJSON() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for PromptProfile.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (p *PromptProfile) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newp, err := ParsePromptProfile(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for PromptProfile.
// It returns the string representation of the enum value as a byte slice
func (p PromptProfile) MarshalText() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PromptProfile.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (p *PromptProfile) UnmarshalText(by []byte) error {
	newp, err := ParsePromptProfile(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// Scan implements the database/sql.Scanner interface for PromptProfile.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (p *PromptProfile) Scan(value any) error {
	newp, err := ParsePromptProfile(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// Value implements the database/sql/driver.Valuer interface for PromptProfile.
// It returns the string representation of the enum value.
func (p PromptProfile) Value() (driver.Value, error) {
	return p.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for PromptProfile.
// It returns the binary representation of the enum value as a byte slice.
func (p PromptProfile) MarshalBinary() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for PromptProfile.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (p *PromptProfile) UnmarshalBinary(by []byte) error {
	newp, err := ParsePromptProfile(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for PromptProfile.
// It returns the string representation of the enum value.
func (p PromptProfile) MarshalYAML() ([]byte, error) {
	return []byte(p.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (p *PromptProfile) UnmarshalYAML(by []byte) error {
	newp, err := ParsePromptProfile(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// promptprofileNames is a constant string slice containing all enum values cononical absolute names
const promptprofileNames = "invalidstandardcompact"

// promptprofileNamesMap is a map of enum values to their canonical absolute
// name positions within the promptprofileNames string slice
var promptprofileNamesMap = map[PromptProfile]string{
	PromptProfiles.INVALID:  promptprofileNames[0:7],
	PromptProfiles.STANDARD: promptprofileNames[7:15],
	PromptProfiles.LEAN:     promptprofileNames[15:22],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (p PromptProfile) String() string {
	if str, ok := promptprofileNamesMap[p]; ok {
		return str
	}
	return fmt.Sprintf("promptprofile(%d)", p.promptProfile)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[invalid]
	_ = x[standard-1]
	_ = x[lean-2]
}
