// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f openai_plan_enum.go

package openai

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// EndpointKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type EndpointKind struct {
	endpointKind
}

// endpointKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the EndpointKind type.
type endpointKindsContainer struct {
	ENDPOINTCHATCOMPLETIONS EndpointKind
	ENDPOINTRESPONSES       EndpointKind
}

// EndpointKinds is a main entry point using the EndpointKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var EndpointKinds = endpointKindsContainer{
	ENDPOINTCHATCOMPLETIONS: EndpointKind{
		endpointKind: endpointChatCompletions,
	},
	ENDPOINTRESPONSES: EndpointKind{
		endpointKind: endpointResponses,
	},
}

// invalidEndpointKind is an invalid sentinel value for EndpointKind
var invalidEndpointKind = EndpointKind{
	endpointKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e endpointKindsContainer) allSlice() []EndpointKind {
	return []EndpointKind{
		EndpointKinds.ENDPOINTCHATCOMPLETIONS,
		EndpointKinds.ENDPOINTRESPONSES,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e endpointKindsContainer) All() iter.Seq[EndpointKind] {
	return func(yield func(EndpointKind) bool) {
		for _, v := range e.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseEndpointKind = errors.New("invalid input provided to parse to EndpointKind")

// ParseEndpointKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseEndpointKind(input any) (EndpointKind, error) {
	switch v := input.(type) {
	case EndpointKind:
		return v, nil
	case string:
		if result := stringToEndpointKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToEndpointKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToEndpointKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToEndpointKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidEndpointKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidEndpointKind, fmt.Errorf("%w: invalid value %v", ErrParseEndpointKind, input)
}

// endpointKindsNameMap is a map of enum values to their EndpointKind representation
// It is used to convert string representations of enum values into their EndpointKind representation.
var endpointKindsNameMap = map[string]EndpointKind{
	"chat_completions": EndpointKinds.ENDPOINTCHATCOMPLETIONS,
	"responses":        EndpointKinds.ENDPOINTRESPONSES,
}

// stringToEndpointKind converts a string representation of an enum value into its EndpointKind representation
// It returns a pointer to the EndpointKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToEndpointKind(s string) *EndpointKind {
	if t, ok := endpointKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToEndpointKind converts a numeric value to a EndpointKind
// It returns a pointer to the EndpointKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToEndpointKind[T constraints.Integer | constraints.Float](num T) *EndpointKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(EndpointKinds.allSlice()) {
		return nil
	}
	result := EndpointKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveEndpointKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveEndpointKinds(f func(EndpointKind)) {
	for _, p := range EndpointKinds.allSlice() {
		f(p)
	}
}

// validEndpointKinds is a map of enum values to their validity
var validEndpointKinds = map[EndpointKind]bool{
	EndpointKinds.ENDPOINTCHATCOMPLETIONS: true,
	EndpointKinds.ENDPOINTRESPONSES:       true,
}

// IsValid checks whether the EndpointKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (e EndpointKind) IsValid() bool {
	return validEndpointKinds[e]
}

// MarshalJSON implements the json.Marshaler interface for EndpointKind.
// It returns the JSON representation of the enum value as a byte slice.
func (e EndpointKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for EndpointKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (e *EndpointKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newe, err := ParseEndpointKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for EndpointKind.
// It returns the string representation of the enum value as a byte slice
func (e EndpointKind) MarshalText() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EndpointKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EndpointKind) UnmarshalText(by []byte) error {
	newe, err := ParseEndpointKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Scan implements the database/sql.Scanner interface for EndpointKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (e *EndpointKind) Scan(value any) error {
	newe, err := ParseEndpointKind(value)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Value implements the database/sql/driver.Valuer interface for EndpointKind.
// It returns the string representation of the enum value.
func (e EndpointKind) Value() (driver.Value, error) {
	return e.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for EndpointKind.
// It returns the binary representation of the enum value as a byte slice.
func (e EndpointKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for EndpointKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EndpointKind) UnmarshalBinary(by []byte) error {
	newe, err := ParseEndpointKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for EndpointKind.
// It returns the string representation of the enum value.
func (e EndpointKind) MarshalYAML() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (e *EndpointKind) UnmarshalYAML(by []byte) error {
	newe, err := ParseEndpointKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// endpointkindNames is a constant string slice containing all enum values cononical absolute names
const endpointkindNames = "chat_completionsresponses"

// endpointkindNamesMap is a map of enum values to their canonical absolute
// name positions within the endpointkindNames string slice
var endpointkindNamesMap = map[EndpointKind]string{
	EndpointKinds.ENDPOINTCHATCOMPLETIONS: endpointkindNames[0:16],
	EndpointKinds.ENDPOINTRESPONSES:       endpointkindNames[16:25],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (e EndpointKind) String() string {
	if str, ok := endpointkindNamesMap[e]; ok {
		return str
	}
	return fmt.Sprintf("endpointkind(%d)", e.endpointKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[endpointChatCompletions]
	_ = x[endpointResponses-1]
}
