// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f openai_plan_enum.go

package openai

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// ReasoningEffort is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ReasoningEffort struct {
	reasoningEffort
}

// reasoningEffortsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ReasoningEffort type.
type reasoningEffortsContainer struct {
	REASONINGEFFORTLOW    ReasoningEffort
	REASONINGEFFORTMEDIUM ReasoningEffort
	REASONINGEFFORTHIGH   ReasoningEffort
	REASONINGEFFORTXHIGH  ReasoningEffort
	REASONINGEFFORTMAX    ReasoningEffort
}

// ReasoningEfforts is a main entry point using the ReasoningEffort type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ReasoningEfforts = reasoningEffortsContainer{
	REASONINGEFFORTLOW: ReasoningEffort{
		reasoningEffort: reasoningEffortLow,
	},
	REASONINGEFFORTMEDIUM: ReasoningEffort{
		reasoningEffort: reasoningEffortMedium,
	},
	REASONINGEFFORTHIGH: ReasoningEffort{
		reasoningEffort: reasoningEffortHigh,
	},
	REASONINGEFFORTXHIGH: ReasoningEffort{
		reasoningEffort: reasoningEffortXHigh,
	},
	REASONINGEFFORTMAX: ReasoningEffort{
		reasoningEffort: reasoningEffortMax,
	},
}

// invalidReasoningEffort is an invalid sentinel value for ReasoningEffort
var invalidReasoningEffort = ReasoningEffort{
	reasoningEffort: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r reasoningEffortsContainer) allSlice() []ReasoningEffort {
	return []ReasoningEffort{
		ReasoningEfforts.REASONINGEFFORTLOW,
		ReasoningEfforts.REASONINGEFFORTMEDIUM,
		ReasoningEfforts.REASONINGEFFORTHIGH,
		ReasoningEfforts.REASONINGEFFORTXHIGH,
		ReasoningEfforts.REASONINGEFFORTMAX,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r reasoningEffortsContainer) All() iter.Seq[ReasoningEffort] {
	return func(yield func(ReasoningEffort) bool) {
		for _, v := range r.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseReasoningEffort = errors.New("invalid input provided to parse to ReasoningEffort")

// ParseReasoningEffort parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseReasoningEffort(input any) (ReasoningEffort, error) {
	switch v := input.(type) {
	case ReasoningEffort:
		return v, nil
	case string:
		if result := stringToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToReasoningEffort(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToReasoningEffort(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToReasoningEffort(v); result != nil {
			return *result, nil
		}
	default:
		return invalidReasoningEffort, fmt.Errorf("invalid type %T", input)
	}
	return invalidReasoningEffort, fmt.Errorf("%w: invalid value %v", ErrParseReasoningEffort, input)
}

// reasoningEffortsNameMap is a map of enum values to their ReasoningEffort representation
// It is used to convert string representations of enum values into their ReasoningEffort representation.
var reasoningEffortsNameMap = map[string]ReasoningEffort{
	"low":    ReasoningEfforts.REASONINGEFFORTLOW,
	"medium": ReasoningEfforts.REASONINGEFFORTMEDIUM,
	"high":   ReasoningEfforts.REASONINGEFFORTHIGH,
	"xhigh":  ReasoningEfforts.REASONINGEFFORTXHIGH,
	"max":    ReasoningEfforts.REASONINGEFFORTMAX,
}

// stringToReasoningEffort converts a string representation of an enum value into its ReasoningEffort representation
// It returns a pointer to the ReasoningEffort representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToReasoningEffort(s string) *ReasoningEffort {
	if t, ok := reasoningEffortsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToReasoningEffort converts a numeric value to a ReasoningEffort
// It returns a pointer to the ReasoningEffort representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToReasoningEffort[T constraints.Integer | constraints.Float](num T) *ReasoningEffort {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ReasoningEfforts.allSlice()) {
		return nil
	}
	result := ReasoningEfforts.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveReasoningEfforts iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveReasoningEfforts(f func(ReasoningEffort)) {
	for _, p := range ReasoningEfforts.allSlice() {
		f(p)
	}
}

// validReasoningEfforts is a map of enum values to their validity
var validReasoningEfforts = map[ReasoningEffort]bool{
	ReasoningEfforts.REASONINGEFFORTLOW:    true,
	ReasoningEfforts.REASONINGEFFORTMEDIUM: true,
	ReasoningEfforts.REASONINGEFFORTHIGH:   true,
	ReasoningEfforts.REASONINGEFFORTXHIGH:  true,
	ReasoningEfforts.REASONINGEFFORTMAX:    true,
}

// IsValid checks whether the ReasoningEfforts value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (r ReasoningEffort) IsValid() bool {
	return validReasoningEfforts[r]
}

// MarshalJSON implements the json.Marshaler interface for ReasoningEffort.
// It returns the JSON representation of the enum value as a byte slice.
func (r ReasoningEffort) MarshalJSON() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReasoningEffort.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (r *ReasoningEffort) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newr, err := ParseReasoningEffort(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ReasoningEffort.
// It returns the string representation of the enum value as a byte slice
func (r ReasoningEffort) MarshalText() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReasoningEffort.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReasoningEffort) UnmarshalText(by []byte) error {
	newr, err := ParseReasoningEffort(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Scan implements the database/sql.Scanner interface for ReasoningEffort.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (r *ReasoningEffort) Scan(value any) error {
	newr, err := ParseReasoningEffort(value)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ReasoningEffort.
// It returns the string representation of the enum value.
func (r ReasoningEffort) Value() (driver.Value, error) {
	return r.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ReasoningEffort.
// It returns the binary representation of the enum value as a byte slice.
func (r ReasoningEffort) MarshalBinary() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ReasoningEffort.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReasoningEffort) UnmarshalBinary(by []byte) error {
	newr, err := ParseReasoningEffort(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ReasoningEffort.
// It returns the string representation of the enum value.
func (r ReasoningEffort) MarshalYAML() ([]byte, error) {
	return []byte(r.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (r *ReasoningEffort) UnmarshalYAML(by []byte) error {
	newr, err := ParseReasoningEffort(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// reasoningeffortNames is a constant string slice containing all enum values cononical absolute names
const reasoningeffortNames = "lowmediumhighxhighmax"

// reasoningeffortNamesMap is a map of enum values to their canonical absolute
// name positions within the reasoningeffortNames string slice
var reasoningeffortNamesMap = map[ReasoningEffort]string{
	ReasoningEfforts.REASONINGEFFORTLOW:    reasoningeffortNames[0:3],
	ReasoningEfforts.REASONINGEFFORTMEDIUM: reasoningeffortNames[3:9],
	ReasoningEfforts.REASONINGEFFORTHIGH:   reasoningeffortNames[9:13],
	ReasoningEfforts.REASONINGEFFORTXHIGH:  reasoningeffortNames[13:18],
	ReasoningEfforts.REASONINGEFFORTMAX:    reasoningeffortNames[18:21],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (r ReasoningEffort) String() string {
	if str, ok := reasoningeffortNamesMap[r]; ok {
		return str
	}
	return fmt.Sprintf("reasoningeffort(%d)", r.reasoningEffort)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[reasoningEffortLow]
	_ = x[reasoningEffortMedium-1]
	_ = x[reasoningEffortHigh-2]
	_ = x[reasoningEffortXHigh-3]
	_ = x[reasoningEffortMax-4]
}
