// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f openai_plan_enum.go

package openai

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// TokenLimitField is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type TokenLimitField struct {
	tokenLimitField
}

// tokenLimitFieldsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the TokenLimitField type.
type tokenLimitFieldsContainer struct {
	TOKENLIMITMAXTOKENS           TokenLimitField
	TOKENLIMITMAXCOMPLETIONTOKENS TokenLimitField
	TOKENLIMITMAXOUTPUTTOKENS     TokenLimitField
}

// TokenLimitFields is a main entry point using the TokenLimitField type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var TokenLimitFields = tokenLimitFieldsContainer{
	TOKENLIMITMAXTOKENS: TokenLimitField{
		tokenLimitField: tokenLimitMaxTokens,
	},
	TOKENLIMITMAXCOMPLETIONTOKENS: TokenLimitField{
		tokenLimitField: tokenLimitMaxCompletionTokens,
	},
	TOKENLIMITMAXOUTPUTTOKENS: TokenLimitField{
		tokenLimitField: tokenLimitMaxOutputTokens,
	},
}

// invalidTokenLimitField is an invalid sentinel value for TokenLimitField
var invalidTokenLimitField = TokenLimitField{
	tokenLimitField: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t tokenLimitFieldsContainer) allSlice() []TokenLimitField {
	return []TokenLimitField{
		TokenLimitFields.TOKENLIMITMAXTOKENS,
		TokenLimitFields.TOKENLIMITMAXCOMPLETIONTOKENS,
		TokenLimitFields.TOKENLIMITMAXOUTPUTTOKENS,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (t tokenLimitFieldsContainer) All() iter.Seq[TokenLimitField] {
	return func(yield func(TokenLimitField) bool) {
		for _, v := range t.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseTokenLimitField = errors.New("invalid input provided to parse to TokenLimitField")

// ParseTokenLimitField parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseTokenLimitField(input any) (TokenLimitField, error) {
	switch v := input.(type) {
	case TokenLimitField:
		return v, nil
	case string:
		if result := stringToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToTokenLimitField(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToTokenLimitField(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToTokenLimitField(v); result != nil {
			return *result, nil
		}
	default:
		return invalidTokenLimitField, fmt.Errorf("invalid type %T", input)
	}
	return invalidTokenLimitField, fmt.Errorf("%w: invalid value %v", ErrParseTokenLimitField, input)
}

// tokenLimitFieldsNameMap is a map of enum values to their TokenLimitField representation
// It is used to convert string representations of enum values into their TokenLimitField representation.
var tokenLimitFieldsNameMap = map[string]TokenLimitField{
	"max_tokens":            TokenLimitFields.TOKENLIMITMAXTOKENS,
	"max_completion_tokens": TokenLimitFields.TOKENLIMITMAXCOMPLETIONTOKENS,
	"max_output_tokens":     TokenLimitFields.TOKENLIMITMAXOUTPUTTOKENS,
}

// stringToTokenLimitField converts a string representation of an enum value into its TokenLimitField representation
// It returns a pointer to the TokenLimitField representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToTokenLimitField(s string) *TokenLimitField {
	if t, ok := tokenLimitFieldsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToTokenLimitField converts a numeric value to a TokenLimitField
// It returns a pointer to the TokenLimitField representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToTokenLimitField[T constraints.Integer | constraints.Float](num T) *TokenLimitField {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(TokenLimitFields.allSlice()) {
		return nil
	}
	result := TokenLimitFields.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveTokenLimitFields iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveTokenLimitFields(f func(TokenLimitField)) {
	for _, p := range TokenLimitFields.allSlice() {
		f(p)
	}
}

// validTokenLimitFields is a map of enum values to their validity
var validTokenLimitFields = map[TokenLimitField]bool{
	TokenLimitFields.TOKENLIMITMAXTOKENS:           true,
	TokenLimitFields.TOKENLIMITMAXCOMPLETIONTOKENS: true,
	TokenLimitFields.TOKENLIMITMAXOUTPUTTOKENS:     true,
}

// IsValid checks whether the TokenLimitFields value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (t TokenLimitField) IsValid() bool {
	return validTokenLimitFields[t]
}

// MarshalJSON implements the json.Marshaler interface for TokenLimitField.
// It returns the JSON representation of the enum value as a byte slice.
func (t TokenLimitField) MarshalJSON() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for TokenLimitField.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (t *TokenLimitField) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newt, err := ParseTokenLimitField(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for TokenLimitField.
// It returns the string representation of the enum value as a byte slice
func (t TokenLimitField) MarshalText() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TokenLimitField.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TokenLimitField) UnmarshalText(by []byte) error {
	newt, err := ParseTokenLimitField(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Scan implements the database/sql.Scanner interface for TokenLimitField.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (t *TokenLimitField) Scan(value any) error {
	newt, err := ParseTokenLimitField(value)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// Value implements the database/sql/driver.Valuer interface for TokenLimitField.
// It returns the string representation of the enum value.
func (t TokenLimitField) Value() (driver.Value, error) {
	return t.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for TokenLimitField.
// It returns the binary representation of the enum value as a byte slice.
func (t TokenLimitField) MarshalBinary() ([]byte, error) {
	return []byte("\"" + t.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for TokenLimitField.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (t *TokenLimitField) UnmarshalBinary(by []byte) error {
	newt, err := ParseTokenLimitField(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for TokenLimitField.
// It returns the string representation of the enum value.
func (t TokenLimitField) MarshalYAML() ([]byte, error) {
	return []byte(t.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (t *TokenLimitField) UnmarshalYAML(by []byte) error {
	newt, err := ParseTokenLimitField(by)
	if err != nil {
		return err
	}
	*t = newt
	return nil
}

// tokenlimitfieldNames is a constant string slice containing all enum values cononical absolute names
const tokenlimitfieldNames = "max_tokensmax_completion_tokensmax_output_tokens"

// tokenlimitfieldNamesMap is a map of enum values to their canonical absolute
// name positions within the tokenlimitfieldNames string slice
var tokenlimitfieldNamesMap = map[TokenLimitField]string{
	TokenLimitFields.TOKENLIMITMAXTOKENS:           tokenlimitfieldNames[0:10],
	TokenLimitFields.TOKENLIMITMAXCOMPLETIONTOKENS: tokenlimitfieldNames[10:31],
	TokenLimitFields.TOKENLIMITMAXOUTPUTTOKENS:     tokenlimitfieldNames[31:48],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (t TokenLimitField) String() string {
	if str, ok := tokenlimitfieldNamesMap[t]; ok {
		return str
	}
	return fmt.Sprintf("tokenlimitfield(%d)", t.tokenLimitField)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[tokenLimitMaxTokens]
	_ = x[tokenLimitMaxCompletionTokens-1]
	_ = x[tokenLimitMaxOutputTokens-2]
}
