// Package genformula renders the zarlcode Homebrew formula from release
// checksums. It is release tooling, invoked from the tag-driven publish
// workflow; users never run it directly.
package genformula

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"text/template"
)

// assetNames maps a platform key to its release archive name template. The
// {{.Version}} placeholder is the full submodule tag, e.g. v0.1.2.
var assetNames = map[string]string{
	"darwin_amd64": "zarlcode_%s_darwin_amd64.tar.gz",
	"darwin_arm64": "zarlcode_%s_darwin_arm64.tar.gz",
	"linux_amd64":  "zarlcode_%s_linux_amd64.tar.gz",
	"linux_arm64":  "zarlcode_%s_linux_arm64.tar.gz",
}

// platform is a single os/arch slot in the formula: the archive to download
// and the checksum to verify it against.
type platform struct {
	AssetName string
	SHA256    string
}

// formula is the template data for one rendered formula.
type formula struct {
	Version     string // full tag, e.g. v0.1.2
	BareVersion string // version without the v prefix, e.g. 0.1.2
	DarwinAMD64 platform
	DarwinARM64 platform
	LinuxAMD64  platform
	LinuxARM64  platform
}

const formulaTemplate = `# Homebrew formula for zarlcode
#
# Generated by tools/genformula.
# Users install with:
#   brew install zarldev/tap/zarlcode

class Zarlcode < Formula
  desc "Terminal coding agent / TUI — plan first, execute second, rewind anytime"
  homepage "https://github.com/zarldev/zarlmono"
  version "{{.BareVersion}}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{{.Version}}/{{.DarwinARM64.AssetName}}"
      sha256 "{{.DarwinARM64.SHA256}}"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{{.Version}}/{{.DarwinAMD64.AssetName}}"
      sha256 "{{.DarwinAMD64.SHA256}}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{{.Version}}/{{.LinuxARM64.AssetName}}"
      sha256 "{{.LinuxARM64.SHA256}}"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{{.Version}}/{{.LinuxAMD64.AssetName}}"
      sha256 "{{.LinuxAMD64.SHA256}}"
    end
  end

  def install
    bin.install "zarlcode"
  end

  test do
    system "#{bin}/zarlcode", "-version"
  end
end
`

var tmpl = template.Must(template.New("formula").Parse(formulaTemplate))

// ParseChecksums reads a checksums file of "<sha256>  <name>" lines and
// returns a name->sha map. Blank lines are skipped.
func ParseChecksums(r io.Reader) (map[string]string, error) {
	values := map[string]string{}
	s := bufio.NewScanner(r)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if line == "" {
			continue
		}
		sha, name, ok := strings.Cut(line, " ")
		if !ok {
			return nil, fmt.Errorf("malformed checksum line: %q", line)
		}
		values[strings.TrimSpace(name)] = sha
	}
	if err := s.Err(); err != nil {
		return nil, fmt.Errorf("scan checksums: %w", err)
	}
	return values, nil
}

// Render produces the formula for version using checksums keyed by archive
// name. It errors if any platform's archive is missing a checksum.
func Render(version string, checksums map[string]string) (string, error) {
	names := map[string]string{}
	var missing []string
	for key, pattern := range assetNames {
		name := fmt.Sprintf(pattern, version)
		names[key] = name
		if _, ok := checksums[name]; !ok {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		return "", fmt.Errorf("missing checksum entries: %s", strings.Join(missing, ", "))
	}

	f := formula{
		Version:     version,
		BareVersion: strings.TrimPrefix(version, "v"),
		DarwinAMD64: platform{AssetName: names["darwin_amd64"], SHA256: checksums[names["darwin_amd64"]]},
		DarwinARM64: platform{AssetName: names["darwin_arm64"], SHA256: checksums[names["darwin_arm64"]]},
		LinuxAMD64:  platform{AssetName: names["linux_amd64"], SHA256: checksums[names["linux_amd64"]]},
		LinuxARM64:  platform{AssetName: names["linux_arm64"], SHA256: checksums[names["linux_arm64"]]},
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, f); err != nil {
		return "", fmt.Errorf("render formula: %w", err)
	}
	return b.String(), nil
}
