package genformula_test

import (
	"strings"
	"testing"

	"github.com/zarldev/zarlmono/tools/genformula"
)

func validChecksums(version string) map[string]string {
	return map[string]string{
		"zarlcode_" + version + "_darwin_amd64.tar.gz": "aaaa",
		"zarlcode_" + version + "_darwin_arm64.tar.gz": "bbbb",
		"zarlcode_" + version + "_linux_amd64.tar.gz":  "cccc",
		"zarlcode_" + version + "_linux_arm64.tar.gz":  "dddd",
	}
}

func TestParseChecksums(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  map[string]string
	}{
		{
			name:  "two space separated",
			input: "aaaa  zarlcode_v0.1.2_linux_amd64.tar.gz\n",
			want:  map[string]string{"zarlcode_v0.1.2_linux_amd64.tar.gz": "aaaa"},
		},
		{
			name:  "skips blank lines",
			input: "\naaaa file_a\n\nbbbb file_b\n\n",
			want:  map[string]string{"file_a": "aaaa", "file_b": "bbbb"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := genformula.ParseChecksums(strings.NewReader(tt.input))
			if err != nil {
				t.Fatalf("ParseChecksums: %v", err)
			}
			if len(got) != len(tt.want) {
				t.Fatalf("got %d entries, want %d", len(got), len(tt.want))
			}
			for name, sha := range tt.want {
				if got[name] != sha {
					t.Errorf("%s: got %q, want %q", name, got[name], sha)
				}
			}
		})
	}
}

func TestRender(t *testing.T) {
	const version = "v0.1.2"
	out, err := genformula.Render(version, validChecksums(version))
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	const header = "# Homebrew formula for zarlcode\n#\n# Generated by tools/genformula.\n"
	if !strings.HasPrefix(out, header) {
		t.Errorf("rendered formula has stale generated header\n--- output ---\n%s", out)
	}
	if !strings.Contains(out, `version "0.1.2"`) {
		t.Errorf("rendered formula does not normalize %q to a bare version\n--- output ---\n%s", version, out)
	}
	if strings.Contains(out, `version "v0.1.2"`) {
		t.Errorf("rendered formula retained the tag prefix in its version\n--- output ---\n%s", out)
	}

	platforms := []struct {
		asset    string
		checksum string
	}{
		{asset: "zarlcode_v0.1.2_darwin_amd64.tar.gz", checksum: "aaaa"},
		{asset: "zarlcode_v0.1.2_darwin_arm64.tar.gz", checksum: "bbbb"},
		{asset: "zarlcode_v0.1.2_linux_amd64.tar.gz", checksum: "cccc"},
		{asset: "zarlcode_v0.1.2_linux_arm64.tar.gz", checksum: "dddd"},
	}
	for _, platform := range platforms {
		want := `url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/` + version + `/` + platform.asset + `"` + "\n" +
			`      sha256 "` + platform.checksum + `"`
		if !strings.Contains(out, want) {
			t.Errorf("rendered formula missing URL and checksum pair %q\n--- output ---\n%s", want, out)
		}
	}
	if got := strings.Count(out, "      url "); got != len(platforms) {
		t.Errorf("rendered formula has %d platform URLs, want %d", got, len(platforms))
	}
	if got := strings.Count(out, "      sha256 "); got != len(platforms) {
		t.Errorf("rendered formula has %d platform checksums, want %d", got, len(platforms))
	}
	if !strings.Contains(out, `system "#{bin}/zarlcode", "-version"`) {
		t.Errorf("rendered formula missing install test\n--- output ---\n%s", out)
	}
}

func TestRenderMissingChecksum(t *testing.T) {
	sums := validChecksums("v0.1.2")
	delete(sums, "zarlcode_v0.1.2_linux_arm64.tar.gz")

	_, err := genformula.Render("v0.1.2", sums)
	if err == nil {
		t.Fatal("Render: expected error for missing checksum, got nil")
	}
	if !strings.Contains(err.Error(), "linux_arm64") {
		t.Errorf("error should name the missing archive: %v", err)
	}
}
