// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums enums.go

package backends

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// AdapterType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type AdapterType struct {
	adapterType
}

// adapterTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the AdapterType type.
type adapterTypesContainer struct {
	OPENAICOMPATIBLE    AdapterType
	DEEPSEEKCOMPATIBLE  AdapterType
	ANTHROPICCOMPATIBLE AdapterType
	GOOGLECOMPATIBLE    AdapterType
	OAUTHOPENAICODEX    AdapterType
	OAUTHCLAUDECODE     AdapterType
	GOOGLEVERTEX        AdapterType
}

// AdapterTypes is a main entry point using the AdapterType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var AdapterTypes = adapterTypesContainer{
	OPENAICOMPATIBLE: AdapterType{
		adapterType: openAICompatible,
	},
	DEEPSEEKCOMPATIBLE: AdapterType{
		adapterType: deepSeekCompatible,
	},
	ANTHROPICCOMPATIBLE: AdapterType{
		adapterType: anthropicCompatible,
	},
	GOOGLECOMPATIBLE: AdapterType{
		adapterType: googleCompatible,
	},
	OAUTHOPENAICODEX: AdapterType{
		adapterType: oauthOpenAICodex,
	},
	OAUTHCLAUDECODE: AdapterType{
		adapterType: oauthClaudeCode,
	},
	GOOGLEVERTEX: AdapterType{
		adapterType: googleVertex,
	},
}

// invalidAdapterType is an invalid sentinel value for AdapterType
var invalidAdapterType = AdapterType{
	adapterType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a adapterTypesContainer) allSlice() []AdapterType {
	return []AdapterType{
		AdapterTypes.OPENAICOMPATIBLE,
		AdapterTypes.DEEPSEEKCOMPATIBLE,
		AdapterTypes.ANTHROPICCOMPATIBLE,
		AdapterTypes.GOOGLECOMPATIBLE,
		AdapterTypes.OAUTHOPENAICODEX,
		AdapterTypes.OAUTHCLAUDECODE,
		AdapterTypes.GOOGLEVERTEX,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a adapterTypesContainer) All() iter.Seq[AdapterType] {
	return func(yield func(AdapterType) bool) {
		for _, v := range a.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

// ParseAdapterType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseAdapterType(input any) (AdapterType, error) {
	switch v := input.(type) {
	case AdapterType:
		return v, nil
	case string:
		if result := stringToAdapterType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToAdapterType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToAdapterType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToAdapterType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidAdapterType, fmt.Errorf("invalid type %T", input)
	}
	return invalidAdapterType, nil
}

// adapterTypesNameMap is a map of enum values to their AdapterType representation
// It is used to convert string representations of enum values into their AdapterType representation.
var adapterTypesNameMap = map[string]AdapterType{
	"openAICompatible":    AdapterTypes.OPENAICOMPATIBLE,
	"deepSeekCompatible":  AdapterTypes.DEEPSEEKCOMPATIBLE,
	"anthropicCompatible": AdapterTypes.ANTHROPICCOMPATIBLE,
	"googleCompatible":    AdapterTypes.GOOGLECOMPATIBLE,
	"oauthOpenAICodex":    AdapterTypes.OAUTHOPENAICODEX,
	"oauthClaudeCode":     AdapterTypes.OAUTHCLAUDECODE,
	"googleVertex":        AdapterTypes.GOOGLEVERTEX,
}

// stringToAdapterType converts a string representation of an enum value into its AdapterType representation
// It returns a pointer to the AdapterType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToAdapterType(s string) *AdapterType {
	if t, ok := adapterTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToAdapterType converts a numeric value to a AdapterType
// It returns a pointer to the AdapterType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToAdapterType[T constraints.Integer | constraints.Float](num T) *AdapterType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(AdapterTypes.allSlice()) {
		return nil
	}
	result := AdapterTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveAdapterTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveAdapterTypes(f func(AdapterType)) {
	for _, p := range AdapterTypes.allSlice() {
		f(p)
	}
}

// validAdapterTypes is a map of enum values to their validity
var validAdapterTypes = map[AdapterType]bool{
	AdapterTypes.OPENAICOMPATIBLE:    true,
	AdapterTypes.DEEPSEEKCOMPATIBLE:  true,
	AdapterTypes.ANTHROPICCOMPATIBLE: true,
	AdapterTypes.GOOGLECOMPATIBLE:    true,
	AdapterTypes.OAUTHOPENAICODEX:    true,
	AdapterTypes.OAUTHCLAUDECODE:     true,
	AdapterTypes.GOOGLEVERTEX:        true,
}

// IsValid checks whether the AdapterTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (a AdapterType) IsValid() bool {
	return validAdapterTypes[a]
}

// MarshalJSON implements the json.Marshaler interface for AdapterType.
// It returns the JSON representation of the enum value as a byte slice.
func (a AdapterType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for AdapterType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (a *AdapterType) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newa, err := ParseAdapterType(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for AdapterType.
// It returns the string representation of the enum value as a byte slice
func (a AdapterType) MarshalText() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AdapterType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *AdapterType) UnmarshalText(by []byte) error {
	newa, err := ParseAdapterType(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Scan implements the database/sql.Scanner interface for AdapterType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (a *AdapterType) Scan(value any) error {
	newa, err := ParseAdapterType(value)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Value implements the database/sql/driver.Valuer interface for AdapterType.
// It returns the string representation of the enum value.
func (a AdapterType) Value() (driver.Value, error) {
	return a.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for AdapterType.
// It returns the binary representation of the enum value as a byte slice.
func (a AdapterType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for AdapterType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *AdapterType) UnmarshalBinary(by []byte) error {
	newa, err := ParseAdapterType(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for AdapterType.
// It returns the string representation of the enum value.
func (a AdapterType) MarshalYAML() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (a *AdapterType) UnmarshalYAML(by []byte) error {
	newa, err := ParseAdapterType(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// adaptertypeNames is a constant string slice containing all enum values cononical absolute names
const adaptertypeNames = "openAICompatibledeepSeekCompatibleanthropicCompatiblegoogleCompatibleoauthOpenAICodexoauthClaudeCodegoogleVertex"

// adaptertypeNamesMap is a map of enum values to their canonical absolute
// name positions within the adaptertypeNames string slice
var adaptertypeNamesMap = map[AdapterType]string{
	AdapterTypes.OPENAICOMPATIBLE:    adaptertypeNames[0:16],
	AdapterTypes.DEEPSEEKCOMPATIBLE:  adaptertypeNames[16:34],
	AdapterTypes.ANTHROPICCOMPATIBLE: adaptertypeNames[34:53],
	AdapterTypes.GOOGLECOMPATIBLE:    adaptertypeNames[53:69],
	AdapterTypes.OAUTHOPENAICODEX:    adaptertypeNames[69:85],
	AdapterTypes.OAUTHCLAUDECODE:     adaptertypeNames[85:100],
	AdapterTypes.GOOGLEVERTEX:        adaptertypeNames[100:112],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (a AdapterType) String() string {
	if str, ok := adaptertypeNamesMap[a]; ok {
		return str
	}
	return fmt.Sprintf("adaptertype(%d)", a.adapterType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [7]struct{}
	_ = x[openAICompatible]
	_ = x[deepSeekCompatible-1]
	_ = x[anthropicCompatible-2]
	_ = x[googleCompatible-3]
	_ = x[oauthOpenAICodex-4]
	_ = x[oauthClaudeCode-5]
	_ = x[googleVertex-6]
}
