// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f agent_task_state_enum.go

package spawn

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// AgentTaskState is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type AgentTaskState struct {
	agentTaskState
}

// agentTaskStatesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the AgentTaskState type.
type agentTaskStatesContainer struct {
	RUNNING   AgentTaskState
	COMPLETED AgentTaskState
	FAILED    AgentTaskState
	CANCELLED AgentTaskState
}

// AgentTaskStates is a main entry point using the AgentTaskState type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var AgentTaskStates = agentTaskStatesContainer{
	RUNNING: AgentTaskState{
		agentTaskState: running,
	},
	COMPLETED: AgentTaskState{
		agentTaskState: completed,
	},
	FAILED: AgentTaskState{
		agentTaskState: failed,
	},
	CANCELLED: AgentTaskState{
		agentTaskState: cancelled,
	},
}

// invalidAgentTaskState is an invalid sentinel value for AgentTaskState
var invalidAgentTaskState = AgentTaskState{
	agentTaskState: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a agentTaskStatesContainer) allSlice() []AgentTaskState {
	return []AgentTaskState{
		AgentTaskStates.RUNNING,
		AgentTaskStates.COMPLETED,
		AgentTaskStates.FAILED,
		AgentTaskStates.CANCELLED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a agentTaskStatesContainer) All() iter.Seq[AgentTaskState] {
	return func(yield func(AgentTaskState) bool) {
		for _, v := range a.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseAgentTaskState = errors.New("invalid input provided to parse to AgentTaskState")

// ParseAgentTaskState parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseAgentTaskState(input any) (AgentTaskState, error) {
	switch v := input.(type) {
	case AgentTaskState:
		return v, nil
	case string:
		if result := stringToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToAgentTaskState(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToAgentTaskState(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToAgentTaskState(v); result != nil {
			return *result, nil
		}
	default:
		return invalidAgentTaskState, fmt.Errorf("invalid type %T", input)
	}
	return invalidAgentTaskState, fmt.Errorf("%w: invalid value %v", ErrParseAgentTaskState, input)
}

// agentTaskStatesNameMap is a map of enum values to their AgentTaskState representation
// It is used to convert string representations of enum values into their AgentTaskState representation.
var agentTaskStatesNameMap = map[string]AgentTaskState{
	"running":   AgentTaskStates.RUNNING,
	"completed": AgentTaskStates.COMPLETED,
	"failed":    AgentTaskStates.FAILED,
	"cancelled": AgentTaskStates.CANCELLED,
}

// stringToAgentTaskState converts a string representation of an enum value into its AgentTaskState representation
// It returns a pointer to the AgentTaskState representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToAgentTaskState(s string) *AgentTaskState {
	if t, ok := agentTaskStatesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToAgentTaskState converts a numeric value to a AgentTaskState
// It returns a pointer to the AgentTaskState representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToAgentTaskState[T constraints.Integer | constraints.Float](num T) *AgentTaskState {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(AgentTaskStates.allSlice()) {
		return nil
	}
	result := AgentTaskStates.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveAgentTaskStates iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveAgentTaskStates(f func(AgentTaskState)) {
	for _, p := range AgentTaskStates.allSlice() {
		f(p)
	}
}

// validAgentTaskStates is a map of enum values to their validity
var validAgentTaskStates = map[AgentTaskState]bool{
	AgentTaskStates.RUNNING:   true,
	AgentTaskStates.COMPLETED: true,
	AgentTaskStates.FAILED:    true,
	AgentTaskStates.CANCELLED: true,
}

// IsValid checks whether the AgentTaskStates value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (a AgentTaskState) IsValid() bool {
	return validAgentTaskStates[a]
}

// MarshalJSON implements the json.Marshaler interface for AgentTaskState.
// It returns the JSON representation of the enum value as a byte slice.
func (a AgentTaskState) MarshalJSON() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for AgentTaskState.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (a *AgentTaskState) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newa, err := ParseAgentTaskState(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for AgentTaskState.
// It returns the string representation of the enum value as a byte slice
func (a AgentTaskState) MarshalText() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AgentTaskState.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *AgentTaskState) UnmarshalText(by []byte) error {
	newa, err := ParseAgentTaskState(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Scan implements the database/sql.Scanner interface for AgentTaskState.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (a *AgentTaskState) Scan(value any) error {
	newa, err := ParseAgentTaskState(value)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Value implements the database/sql/driver.Valuer interface for AgentTaskState.
// It returns the string representation of the enum value.
func (a AgentTaskState) Value() (driver.Value, error) {
	return a.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for AgentTaskState.
// It returns the binary representation of the enum value as a byte slice.
func (a AgentTaskState) MarshalBinary() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for AgentTaskState.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *AgentTaskState) UnmarshalBinary(by []byte) error {
	newa, err := ParseAgentTaskState(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for AgentTaskState.
// It returns the string representation of the enum value.
func (a AgentTaskState) MarshalYAML() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (a *AgentTaskState) UnmarshalYAML(by []byte) error {
	newa, err := ParseAgentTaskState(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// agenttaskstateNames is a constant string slice containing all enum values cononical absolute names
const agenttaskstateNames = "runningcompletedfailedcancelled"

// agenttaskstateNamesMap is a map of enum values to their canonical absolute
// name positions within the agenttaskstateNames string slice
var agenttaskstateNamesMap = map[AgentTaskState]string{
	AgentTaskStates.RUNNING:   agenttaskstateNames[0:7],
	AgentTaskStates.COMPLETED: agenttaskstateNames[7:16],
	AgentTaskStates.FAILED:    agenttaskstateNames[16:22],
	AgentTaskStates.CANCELLED: agenttaskstateNames[22:31],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (a AgentTaskState) String() string {
	if str, ok := agenttaskstateNamesMap[a]; ok {
		return str
	}
	return fmt.Sprintf("agenttaskstate(%d)", a.agentTaskState)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [5]struct{}
	_ = x[running-1]
	_ = x[completed-2]
	_ = x[failed-3]
	_ = x[cancelled-4]
}
