// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f api_key_storage_enum.go

package db

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// APIKeyStorage is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type APIKeyStorage struct {
	apiKeyStorage
}

// apiKeyStoragesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the APIKeyStorage type.
type apiKeyStoragesContainer struct {
	INVALID   APIKeyStorage
	VAULT     APIKeyStorage
	PLAINTEXT APIKeyStorage
}

// APIKeyStorages is a main entry point using the APIKeyStorage type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var APIKeyStorages = apiKeyStoragesContainer{
	INVALID: APIKeyStorage{
		apiKeyStorage: invalid,
	},
	VAULT: APIKeyStorage{
		apiKeyStorage: vault,
	},
	PLAINTEXT: APIKeyStorage{
		apiKeyStorage: plaintext,
	},
}

// invalidAPIKeyStorage is an invalid sentinel value for APIKeyStorage
var invalidAPIKeyStorage = APIKeyStorage{
	apiKeyStorage: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a apiKeyStoragesContainer) allSlice() []APIKeyStorage {
	return []APIKeyStorage{
		APIKeyStorages.VAULT,
		APIKeyStorages.PLAINTEXT,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a apiKeyStoragesContainer) All() iter.Seq[APIKeyStorage] {
	return func(yield func(APIKeyStorage) bool) {
		for _, v := range a.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseAPIKeyStorage = errors.New("invalid input provided to parse to APIKeyStorage")

// ParseAPIKeyStorage parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseAPIKeyStorage(input any) (APIKeyStorage, error) {
	switch v := input.(type) {
	case APIKeyStorage:
		return v, nil
	case string:
		if result := stringToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToAPIKeyStorage(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToAPIKeyStorage(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToAPIKeyStorage(v); result != nil {
			return *result, nil
		}
	default:
		return invalidAPIKeyStorage, fmt.Errorf("invalid type %T", input)
	}
	return invalidAPIKeyStorage, fmt.Errorf("%w: invalid value %v", ErrParseAPIKeyStorage, input)
}

// apiKeyStoragesNameMap is a map of enum values to their APIKeyStorage representation
// It is used to convert string representations of enum values into their APIKeyStorage representation.
var apiKeyStoragesNameMap = map[string]APIKeyStorage{
	"invalid":   APIKeyStorages.INVALID,
	"vault":     APIKeyStorages.VAULT,
	"plaintext": APIKeyStorages.PLAINTEXT,
}

// stringToAPIKeyStorage converts a string representation of an enum value into its APIKeyStorage representation
// It returns a pointer to the APIKeyStorage representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToAPIKeyStorage(s string) *APIKeyStorage {
	if t, ok := apiKeyStoragesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToAPIKeyStorage converts a numeric value to a APIKeyStorage
// It returns a pointer to the APIKeyStorage representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToAPIKeyStorage[T constraints.Integer | constraints.Float](num T) *APIKeyStorage {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(APIKeyStorages.allSlice()) {
		return nil
	}
	result := APIKeyStorages.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveAPIKeyStorages iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveAPIKeyStorages(f func(APIKeyStorage)) {
	for _, p := range APIKeyStorages.allSlice() {
		f(p)
	}
}

// validAPIKeyStorages is a map of enum values to their validity
var validAPIKeyStorages = map[APIKeyStorage]bool{
	APIKeyStorages.INVALID:   false,
	APIKeyStorages.VAULT:     true,
	APIKeyStorages.PLAINTEXT: true,
}

// IsValid checks whether the APIKeyStorages value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (a APIKeyStorage) IsValid() bool {
	return validAPIKeyStorages[a]
}

// MarshalJSON implements the json.Marshaler interface for APIKeyStorage.
// It returns the JSON representation of the enum value as a byte slice.
func (a APIKeyStorage) MarshalJSON() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for APIKeyStorage.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (a *APIKeyStorage) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newa, err := ParseAPIKeyStorage(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for APIKeyStorage.
// It returns the string representation of the enum value as a byte slice
func (a APIKeyStorage) MarshalText() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for APIKeyStorage.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *APIKeyStorage) UnmarshalText(by []byte) error {
	newa, err := ParseAPIKeyStorage(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Scan implements the database/sql.Scanner interface for APIKeyStorage.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (a *APIKeyStorage) Scan(value any) error {
	newa, err := ParseAPIKeyStorage(value)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Value implements the database/sql/driver.Valuer interface for APIKeyStorage.
// It returns the string representation of the enum value.
func (a APIKeyStorage) Value() (driver.Value, error) {
	return a.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for APIKeyStorage.
// It returns the binary representation of the enum value as a byte slice.
func (a APIKeyStorage) MarshalBinary() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for APIKeyStorage.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *APIKeyStorage) UnmarshalBinary(by []byte) error {
	newa, err := ParseAPIKeyStorage(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for APIKeyStorage.
// It returns the string representation of the enum value.
func (a APIKeyStorage) MarshalYAML() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (a *APIKeyStorage) UnmarshalYAML(by []byte) error {
	newa, err := ParseAPIKeyStorage(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// apikeystorageNames is a constant string slice containing all enum values cononical absolute names
const apikeystorageNames = "invalidvaultplaintext"

// apikeystorageNamesMap is a map of enum values to their canonical absolute
// name positions within the apikeystorageNames string slice
var apikeystorageNamesMap = map[APIKeyStorage]string{
	APIKeyStorages.INVALID:   apikeystorageNames[0:7],
	APIKeyStorages.VAULT:     apikeystorageNames[7:12],
	APIKeyStorages.PLAINTEXT: apikeystorageNames[12:21],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (a APIKeyStorage) String() string {
	if str, ok := apikeystorageNamesMap[a]; ok {
		return str
	}
	return fmt.Sprintf("apikeystorage(%d)", a.apiKeyStorage)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[invalid]
	_ = x[vault-1]
	_ = x[plaintext-2]
}
