// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f activity_phase_enum.go

package tui

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// ActivityPhase is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ActivityPhase struct {
	activityPhase
}

// activityPhasesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ActivityPhase type.
type activityPhasesContainer struct {
	ACTIVITYWORKING    ActivityPhase
	ACTIVITYTHINKING   ActivityPhase
	ACTIVITYRESPONDING ActivityPhase
}

// ActivityPhases is a main entry point using the ActivityPhase type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ActivityPhases = activityPhasesContainer{
	ACTIVITYWORKING: ActivityPhase{
		activityPhase: activityWorking,
	},
	ACTIVITYTHINKING: ActivityPhase{
		activityPhase: activityThinking,
	},
	ACTIVITYRESPONDING: ActivityPhase{
		activityPhase: activityResponding,
	},
}

// invalidActivityPhase is an invalid sentinel value for ActivityPhase
var invalidActivityPhase = ActivityPhase{
	activityPhase: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a activityPhasesContainer) allSlice() []ActivityPhase {
	return []ActivityPhase{
		ActivityPhases.ACTIVITYWORKING,
		ActivityPhases.ACTIVITYTHINKING,
		ActivityPhases.ACTIVITYRESPONDING,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (a activityPhasesContainer) All() iter.Seq[ActivityPhase] {
	return func(yield func(ActivityPhase) bool) {
		for _, v := range a.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseActivityPhase = errors.New("invalid input provided to parse to ActivityPhase")

// ParseActivityPhase parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseActivityPhase(input any) (ActivityPhase, error) {
	switch v := input.(type) {
	case ActivityPhase:
		return v, nil
	case string:
		if result := stringToActivityPhase(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToActivityPhase(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToActivityPhase(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToActivityPhase(v); result != nil {
			return *result, nil
		}
	default:
		return invalidActivityPhase, fmt.Errorf("invalid type %T", input)
	}
	return invalidActivityPhase, fmt.Errorf("%w: invalid value %v", ErrParseActivityPhase, input)
}

// activityPhasesNameMap is a map of enum values to their ActivityPhase representation
// It is used to convert string representations of enum values into their ActivityPhase representation.
var activityPhasesNameMap = map[string]ActivityPhase{
	"working":    ActivityPhases.ACTIVITYWORKING,
	"thinking":   ActivityPhases.ACTIVITYTHINKING,
	"responding": ActivityPhases.ACTIVITYRESPONDING,
}

// stringToActivityPhase converts a string representation of an enum value into its ActivityPhase representation
// It returns a pointer to the ActivityPhase representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToActivityPhase(s string) *ActivityPhase {
	if t, ok := activityPhasesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToActivityPhase converts a numeric value to a ActivityPhase
// It returns a pointer to the ActivityPhase representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToActivityPhase[T constraints.Integer | constraints.Float](num T) *ActivityPhase {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ActivityPhases.allSlice()) {
		return nil
	}
	result := ActivityPhases.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveActivityPhases iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveActivityPhases(f func(ActivityPhase)) {
	for _, p := range ActivityPhases.allSlice() {
		f(p)
	}
}

// validActivityPhases is a map of enum values to their validity
var validActivityPhases = map[ActivityPhase]bool{
	ActivityPhases.ACTIVITYWORKING:    true,
	ActivityPhases.ACTIVITYTHINKING:   true,
	ActivityPhases.ACTIVITYRESPONDING: true,
}

// IsValid checks whether the ActivityPhases value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (a ActivityPhase) IsValid() bool {
	return validActivityPhases[a]
}

// MarshalJSON implements the json.Marshaler interface for ActivityPhase.
// It returns the JSON representation of the enum value as a byte slice.
func (a ActivityPhase) MarshalJSON() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ActivityPhase.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (a *ActivityPhase) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newa, err := ParseActivityPhase(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ActivityPhase.
// It returns the string representation of the enum value as a byte slice
func (a ActivityPhase) MarshalText() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ActivityPhase.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *ActivityPhase) UnmarshalText(by []byte) error {
	newa, err := ParseActivityPhase(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Scan implements the database/sql.Scanner interface for ActivityPhase.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (a *ActivityPhase) Scan(value any) error {
	newa, err := ParseActivityPhase(value)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ActivityPhase.
// It returns the string representation of the enum value.
func (a ActivityPhase) Value() (driver.Value, error) {
	return a.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ActivityPhase.
// It returns the binary representation of the enum value as a byte slice.
func (a ActivityPhase) MarshalBinary() ([]byte, error) {
	return []byte("\"" + a.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ActivityPhase.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (a *ActivityPhase) UnmarshalBinary(by []byte) error {
	newa, err := ParseActivityPhase(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ActivityPhase.
// It returns the string representation of the enum value.
func (a ActivityPhase) MarshalYAML() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (a *ActivityPhase) UnmarshalYAML(by []byte) error {
	newa, err := ParseActivityPhase(by)
	if err != nil {
		return err
	}
	*a = newa
	return nil
}

// activityphaseNames is a constant string slice containing all enum values cononical absolute names
const activityphaseNames = "workingthinkingresponding"

// activityphaseNamesMap is a map of enum values to their canonical absolute
// name positions within the activityphaseNames string slice
var activityphaseNamesMap = map[ActivityPhase]string{
	ActivityPhases.ACTIVITYWORKING:    activityphaseNames[0:7],
	ActivityPhases.ACTIVITYTHINKING:   activityphaseNames[7:15],
	ActivityPhases.ACTIVITYRESPONDING: activityphaseNames[15:25],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (a ActivityPhase) String() string {
	if str, ok := activityphaseNamesMap[a]; ok {
		return str
	}
	return fmt.Sprintf("activityphase(%d)", a.activityPhase)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[activityWorking-1]
	_ = x[activityThinking-2]
	_ = x[activityResponding-3]
}
