// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f command_id_enum.go

package tui

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// CommandID is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type CommandID struct {
	commandID
}

// commandIDsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the CommandID type.
type commandIDsContainer struct {
	COMMANDHELP             CommandID
	COMMANDSETTINGS         CommandID
	COMMANDTHEME            CommandID
	COMMANDMODELS           CommandID
	COMMANDNAMESESSION      CommandID
	COMMANDPLAN             CommandID
	COMMANDTOOLHISTORY      CommandID
	COMMANDFILES            CommandID
	COMMANDCOPYLASTRESPONSE CommandID
	COMMANDEXPORTSESSION    CommandID
}

// CommandIDs is a main entry point using the CommandID type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var CommandIDs = commandIDsContainer{
	COMMANDHELP: CommandID{
		commandID: commandHelp,
	},
	COMMANDSETTINGS: CommandID{
		commandID: commandSettings,
	},
	COMMANDTHEME: CommandID{
		commandID: commandTheme,
	},
	COMMANDMODELS: CommandID{
		commandID: commandModels,
	},
	COMMANDNAMESESSION: CommandID{
		commandID: commandNameSession,
	},
	COMMANDPLAN: CommandID{
		commandID: commandPlan,
	},
	COMMANDTOOLHISTORY: CommandID{
		commandID: commandToolHistory,
	},
	COMMANDFILES: CommandID{
		commandID: commandFiles,
	},
	COMMANDCOPYLASTRESPONSE: CommandID{
		commandID: commandCopyLastResponse,
	},
	COMMANDEXPORTSESSION: CommandID{
		commandID: commandExportSession,
	},
}

// invalidCommandID is an invalid sentinel value for CommandID
var invalidCommandID = CommandID{
	commandID: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c commandIDsContainer) allSlice() []CommandID {
	return []CommandID{
		CommandIDs.COMMANDHELP,
		CommandIDs.COMMANDSETTINGS,
		CommandIDs.COMMANDTHEME,
		CommandIDs.COMMANDMODELS,
		CommandIDs.COMMANDNAMESESSION,
		CommandIDs.COMMANDPLAN,
		CommandIDs.COMMANDTOOLHISTORY,
		CommandIDs.COMMANDFILES,
		CommandIDs.COMMANDCOPYLASTRESPONSE,
		CommandIDs.COMMANDEXPORTSESSION,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c commandIDsContainer) All() iter.Seq[CommandID] {
	return func(yield func(CommandID) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseCommandID = errors.New("invalid input provided to parse to CommandID")

// ParseCommandID parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseCommandID(input any) (CommandID, error) {
	switch v := input.(type) {
	case CommandID:
		return v, nil
	case string:
		if result := stringToCommandID(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToCommandID(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToCommandID(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToCommandID(v); result != nil {
			return *result, nil
		}
	default:
		return invalidCommandID, fmt.Errorf("invalid type %T", input)
	}
	return invalidCommandID, fmt.Errorf("%w: invalid value %v", ErrParseCommandID, input)
}

// commandIDsNameMap is a map of enum values to their CommandID representation
// It is used to convert string representations of enum values into their CommandID representation.
var commandIDsNameMap = map[string]CommandID{
	"help":               CommandIDs.COMMANDHELP,
	"settings":           CommandIDs.COMMANDSETTINGS,
	"theme":              CommandIDs.COMMANDTHEME,
	"models":             CommandIDs.COMMANDMODELS,
	"name-session":       CommandIDs.COMMANDNAMESESSION,
	"plan":               CommandIDs.COMMANDPLAN,
	"tool-history":       CommandIDs.COMMANDTOOLHISTORY,
	"files":              CommandIDs.COMMANDFILES,
	"copy-last-response": CommandIDs.COMMANDCOPYLASTRESPONSE,
	"export-session":     CommandIDs.COMMANDEXPORTSESSION,
}

// stringToCommandID converts a string representation of an enum value into its CommandID representation
// It returns a pointer to the CommandID representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToCommandID(s string) *CommandID {
	if t, ok := commandIDsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToCommandID converts a numeric value to a CommandID
// It returns a pointer to the CommandID representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToCommandID[T constraints.Integer | constraints.Float](num T) *CommandID {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(CommandIDs.allSlice()) {
		return nil
	}
	result := CommandIDs.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveCommandIDs iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveCommandIDs(f func(CommandID)) {
	for _, p := range CommandIDs.allSlice() {
		f(p)
	}
}

// validCommandIDs is a map of enum values to their validity
var validCommandIDs = map[CommandID]bool{
	CommandIDs.COMMANDHELP:             true,
	CommandIDs.COMMANDSETTINGS:         true,
	CommandIDs.COMMANDTHEME:            true,
	CommandIDs.COMMANDMODELS:           true,
	CommandIDs.COMMANDNAMESESSION:      true,
	CommandIDs.COMMANDPLAN:             true,
	CommandIDs.COMMANDTOOLHISTORY:      true,
	CommandIDs.COMMANDFILES:            true,
	CommandIDs.COMMANDCOPYLASTRESPONSE: true,
	CommandIDs.COMMANDEXPORTSESSION:    true,
}

// IsValid checks whether the CommandIDs value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (c CommandID) IsValid() bool {
	return validCommandIDs[c]
}

// MarshalJSON implements the json.Marshaler interface for CommandID.
// It returns the JSON representation of the enum value as a byte slice.
func (c CommandID) MarshalJSON() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for CommandID.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (c *CommandID) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newc, err := ParseCommandID(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for CommandID.
// It returns the string representation of the enum value as a byte slice
func (c CommandID) MarshalText() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for CommandID.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *CommandID) UnmarshalText(by []byte) error {
	newc, err := ParseCommandID(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Scan implements the database/sql.Scanner interface for CommandID.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (c *CommandID) Scan(value any) error {
	newc, err := ParseCommandID(value)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Value implements the database/sql/driver.Valuer interface for CommandID.
// It returns the string representation of the enum value.
func (c CommandID) Value() (driver.Value, error) {
	return c.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for CommandID.
// It returns the binary representation of the enum value as a byte slice.
func (c CommandID) MarshalBinary() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for CommandID.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *CommandID) UnmarshalBinary(by []byte) error {
	newc, err := ParseCommandID(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for CommandID.
// It returns the string representation of the enum value.
func (c CommandID) MarshalYAML() ([]byte, error) {
	return []byte(c.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (c *CommandID) UnmarshalYAML(by []byte) error {
	newc, err := ParseCommandID(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// commandidNames is a constant string slice containing all enum values cononical absolute names
const commandidNames = "helpsettingsthememodelsname-sessionplantool-historyfilescopy-last-responseexport-session"

// commandidNamesMap is a map of enum values to their canonical absolute
// name positions within the commandidNames string slice
var commandidNamesMap = map[CommandID]string{
	CommandIDs.COMMANDHELP:             commandidNames[0:4],
	CommandIDs.COMMANDSETTINGS:         commandidNames[4:12],
	CommandIDs.COMMANDTHEME:            commandidNames[12:17],
	CommandIDs.COMMANDMODELS:           commandidNames[17:23],
	CommandIDs.COMMANDNAMESESSION:      commandidNames[23:35],
	CommandIDs.COMMANDPLAN:             commandidNames[35:39],
	CommandIDs.COMMANDTOOLHISTORY:      commandidNames[39:51],
	CommandIDs.COMMANDFILES:            commandidNames[51:56],
	CommandIDs.COMMANDCOPYLASTRESPONSE: commandidNames[56:74],
	CommandIDs.COMMANDEXPORTSESSION:    commandidNames[74:88],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (c CommandID) String() string {
	if str, ok := commandidNamesMap[c]; ok {
		return str
	}
	return fmt.Sprintf("commandid(%d)", c.commandID)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [10]struct{}
	_ = x[commandHelp]
	_ = x[commandSettings-1]
	_ = x[commandTheme-2]
	_ = x[commandModels-3]
	_ = x[commandNameSession-4]
	_ = x[commandPlan-5]
	_ = x[commandToolHistory-6]
	_ = x[commandFiles-7]
	_ = x[commandCopyLastResponse-8]
	_ = x[commandExportSession-9]
}
