// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f scope_enum.go

package prefs

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// Scope is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type Scope struct {
	scope
}

// scopesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the Scope type.
type scopesContainer struct {
	INVALID   Scope
	WORKSPACE Scope
	GLOBAL    Scope
	EFFECTIVE Scope
}

// Scopes is a main entry point using the Scope type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Scopes = scopesContainer{
	INVALID: Scope{
		scope: invalid,
	},
	WORKSPACE: Scope{
		scope: workspace,
	},
	GLOBAL: Scope{
		scope: global,
	},
	EFFECTIVE: Scope{
		scope: effective,
	},
}

// invalidScope is an invalid sentinel value for Scope
var invalidScope = Scope{
	scope: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s scopesContainer) allSlice() []Scope {
	return []Scope{
		Scopes.WORKSPACE,
		Scopes.GLOBAL,
		Scopes.EFFECTIVE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (s scopesContainer) All() iter.Seq[Scope] {
	return func(yield func(Scope) bool) {
		for _, v := range s.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseScope = errors.New("invalid input provided to parse to Scope")

// ParseScope parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseScope(input any) (Scope, error) {
	switch v := input.(type) {
	case Scope:
		return v, nil
	case string:
		if result := stringToScope(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToScope(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToScope(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToScope(v); result != nil {
			return *result, nil
		}
	default:
		return invalidScope, fmt.Errorf("invalid type %T", input)
	}
	return invalidScope, fmt.Errorf("%w: invalid value %v", ErrParseScope, input)
}

// scopesNameMap is a map of enum values to their Scope representation
// It is used to convert string representations of enum values into their Scope representation.
var scopesNameMap = map[string]Scope{
	"invalid":   Scopes.INVALID,
	"workspace": Scopes.WORKSPACE,
	"global":    Scopes.GLOBAL,
	"effective": Scopes.EFFECTIVE,
}

// stringToScope converts a string representation of an enum value into its Scope representation
// It returns a pointer to the Scope representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToScope(s string) *Scope {
	if t, ok := scopesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToScope converts a numeric value to a Scope
// It returns a pointer to the Scope representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToScope[T constraints.Integer | constraints.Float](num T) *Scope {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(Scopes.allSlice()) {
		return nil
	}
	result := Scopes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveScopes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveScopes(f func(Scope)) {
	for _, p := range Scopes.allSlice() {
		f(p)
	}
}

// validScopes is a map of enum values to their validity
var validScopes = map[Scope]bool{
	Scopes.INVALID:   false,
	Scopes.WORKSPACE: true,
	Scopes.GLOBAL:    true,
	Scopes.EFFECTIVE: true,
}

// IsValid checks whether the Scopes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (s Scope) IsValid() bool {
	return validScopes[s]
}

// MarshalJSON implements the json.Marshaler interface for Scope.
// It returns the JSON representation of the enum value as a byte slice.
func (s Scope) MarshalJSON() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Scope.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (s *Scope) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	news, err := ParseScope(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Scope.
// It returns the string representation of the enum value as a byte slice
func (s Scope) MarshalText() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Scope.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *Scope) UnmarshalText(by []byte) error {
	news, err := ParseScope(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Scan implements the database/sql.Scanner interface for Scope.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (s *Scope) Scan(value any) error {
	news, err := ParseScope(value)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// Value implements the database/sql/driver.Valuer interface for Scope.
// It returns the string representation of the enum value.
func (s Scope) Value() (driver.Value, error) {
	return s.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Scope.
// It returns the binary representation of the enum value as a byte slice.
func (s Scope) MarshalBinary() ([]byte, error) {
	return []byte("\"" + s.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Scope.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (s *Scope) UnmarshalBinary(by []byte) error {
	news, err := ParseScope(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for Scope.
// It returns the string representation of the enum value.
func (s Scope) MarshalYAML() ([]byte, error) {
	return []byte(s.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (s *Scope) UnmarshalYAML(by []byte) error {
	news, err := ParseScope(by)
	if err != nil {
		return err
	}
	*s = news
	return nil
}

// scopeNames is a constant string slice containing all enum values cononical absolute names
const scopeNames = "invalidworkspaceglobaleffective"

// scopeNamesMap is a map of enum values to their canonical absolute
// name positions within the scopeNames string slice
var scopeNamesMap = map[Scope]string{
	Scopes.INVALID:   scopeNames[0:7],
	Scopes.WORKSPACE: scopeNames[7:16],
	Scopes.GLOBAL:    scopeNames[16:22],
	Scopes.EFFECTIVE: scopeNames[22:31],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (s Scope) String() string {
	if str, ok := scopeNamesMap[s]; ok {
		return str
	}
	return fmt.Sprintf("scope(%d)", s.scope)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [4]struct{}
	_ = x[invalid]
	_ = x[workspace-1]
	_ = x[global-2]
	_ = x[effective-3]
}
