package retrieval

import (
	"context"
	"fmt"
	"strings"

	"github.com/zarldev/zarlmono/zkit/sourcecode"
)

// SyntaxChunker splits source files by structural AST boundaries. For Go
// files it uses go/parser+go/ast via sourcecode.GoParser — zero CGO, zero
// WASM, stdlib only. Files that fail to parse or whose language is not
// supported fall back to a TextChunker.
//
// Each chunk's metadata carries:
//
//	kind         — "func", "method", or "type"
//	name         — the declared identifier
//	receiver     — (methods only) the receiver type name
//	start_line   — 1-based line of the first declaration token
//	end_line     — 1-based line after the last declaration token
//
// The chunk Text is the exact source bytes of the declaration, extracted via
// parser offsets — no reformatting, no loss.
type SyntaxChunker struct {
	// Size is the per-chunk source-byte target used only by the fallback.
	// Zero means every structural unit becomes its own chunk (no size-based
	// splitting of large declarations).
	Size int

	// Overlap is passed through to the fallback TextChunker.
	Overlap int

	// Languages lists lowercase file extensions that should be parsed
	// structurally. Default: ["go"]. Future entries ("py", "ts", "rs", etc.)
	// will route to tree-sitter backends keyed by this same field.
	Languages []string

	// SkipGenerated skips Go files detected as generated (the
	// "Code generated by" comment convention). The zero value of
	// SyntaxChunker (no Languages set) defaults to true for safety.
	// When Languages is explicitly configured, this field is used
	// as-is.
	SkipGenerated bool
}

// SourceDocument is a typed source file input for syntax chunking.
type SourceDocument struct {
	ID       DocumentID
	Text     string
	Path     string
	Ext      string
	Language sourcecode.Language
}

// SourceChunk is a typed syntax chunk with sourcecode metadata.
type SourceChunk struct {
	ID       DocumentID
	Text     string
	Path     string
	Symbol   sourcecode.Symbol
	Kind     sourcecode.SymbolKind
	Receiver string
}

// ChunkSource splits typed source documents by structural AST boundaries. It
// returns only parser-backed chunks; unsupported languages and parse errors are
// reported instead of falling back to opaque text chunks.
func (c SyntaxChunker) ChunkSource(ctx context.Context, docs []SourceDocument) ([]SourceChunk, error) {
	useDefaults := c.Languages == nil
	langs := c.Languages
	if len(langs) == 0 {
		langs = []string{"go"}
	}
	langSet := make(map[string]struct{}, len(langs))
	for _, l := range langs {
		langSet[strings.ToLower(l)] = struct{}{}
	}
	skipGen := c.SkipGenerated
	if useDefaults {
		skipGen = true
	}

	var out []SourceChunk
	for i := range docs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		doc := docs[i]
		ext := inferSourceExt(doc)
		if _, ok := langSet[ext]; !ok {
			continue
		}
		if ext == "go" {
			chunks, err := c.chunkGoSource(doc, skipGen)
			if err != nil {
				return nil, err
			}
			out = append(out, chunks...)
		}
	}
	return out, nil
}

func inferSourceExt(doc SourceDocument) string {
	if doc.Ext != "" {
		return strings.ToLower(strings.TrimPrefix(doc.Ext, "."))
	}
	if doc.Language != "" {
		return strings.ToLower(string(doc.Language))
	}
	id := string(doc.ID)
	if i := strings.LastIndexByte(id, '.'); i >= 0 && i < len(id)-1 {
		return strings.ToLower(id[i+1:])
	}
	return ""
}

func (c SyntaxChunker) chunkGoSource(doc SourceDocument, skipGen bool) ([]SourceChunk, error) {
	src := doc.Text
	if strings.TrimSpace(src) == "" {
		return nil, nil
	}
	path := doc.Path
	if path == "" {
		path = string(doc.ID)
	}
	parsed, err := (sourcecode.GoParser{}).Parse(path, []byte(src))
	if err != nil {
		return nil, err
	}
	if skipGen && parsed.Generated {
		return nil, nil
	}
	chunks := make([]SourceChunk, 0, len(parsed.Symbols))
	for _, sym := range parsed.Symbols {
		if !syntaxChunkableKind(sym.Kind) {
			continue
		}
		if sym.StartOffset < 0 || sym.EndOffset > len(src) || sym.StartOffset >= sym.EndOffset {
			continue
		}
		kind := sym.Kind
		if kind.IsType() {
			kind = sourcecode.SymbolKindType
		}
		id := doc.ID
		if id != "" {
			id = DocumentID(fmt.Sprintf("%s:%s:%d-%d", doc.ID, sym.Name, sym.StartLine, sym.EndLine))
		}
		chunks = append(chunks, SourceChunk{
			ID:       id,
			Text:     src[sym.StartOffset:sym.EndOffset],
			Path:     path,
			Symbol:   sym,
			Kind:     kind,
			Receiver: sym.Receiver,
		})
	}
	return chunks, nil
}

// Chunk splits each document by structural AST boundaries.
func (c SyntaxChunker) Chunk(ctx context.Context, docs []Document) ([]Document, error) {
	// Defaults: when the caller uses the zero-value Languages (nil slice), we
	// also default SkipGenerated to true for safety. Explicit Languages
	// configuration leaves SkipGenerated as-is.
	useDefaults := c.Languages == nil
	langs := c.Languages
	if len(langs) == 0 {
		langs = []string{"go"}
	}
	langSet := make(map[string]struct{}, len(langs))
	for _, l := range langs {
		langSet[strings.ToLower(l)] = struct{}{}
	}
	skipGen := c.SkipGenerated
	if useDefaults {
		skipGen = true
	}

	// Fallback: when Size is zero we still need a working chunker for
	// non-Go files and parse errors. Use a safe minimum so
	// TextChunker never rejects input.
	fallbackSize := c.Size
	if fallbackSize <= 0 {
		fallbackSize = 2048
	}
	fallback := TextChunker{Size: fallbackSize, Overlap: c.Overlap}

	var out []Document
	for i := range docs {
		doc := &docs[i]
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		ext := c.inferExt(doc)
		if _, ok := langSet[ext]; !ok {
			chunks, err := fallback.Chunk(ctx, []Document{*doc})
			if err != nil {
				return nil, err
			}
			out = append(out, chunks...)
			continue
		}

		switch ext {
		case "go":
			chunks, err := c.chunkGo(*doc, skipGen)
			if err != nil {
				fb, fbErr := fallback.Chunk(ctx, []Document{*doc})
				if fbErr != nil {
					return nil, fmt.Errorf("syntax chunk go: %w (fallback also failed: %s)", err, fbErr.Error())
				}
				out = append(out, fb...)
				continue
			}
			out = append(out, chunks...)
		default:
			chunks, err := fallback.Chunk(ctx, []Document{*doc})
			if err != nil {
				return nil, err
			}
			out = append(out, chunks...)
		}
	}
	return out, nil
}

// inferExt returns the lowercase file extension for a document.
func (c SyntaxChunker) inferExt(doc *Document) string {
	if doc.Metadata != nil {
		if ext, ok := doc.Metadata["ext"].(string); ok && ext != "" {
			return strings.ToLower(strings.TrimPrefix(ext, "."))
		}
		if lang, ok := doc.Metadata["language"].(string); ok && lang != "" {
			return strings.ToLower(lang)
		}
	}
	id := string(doc.ID)
	if i := strings.LastIndexByte(id, '.'); i >= 0 && i < len(id)-1 {
		return strings.ToLower(id[i+1:])
	}
	return ""
}

// chunkGo parses a single Go source document and returns one chunk per
// top-level func, method, or named type declaration.
func (c SyntaxChunker) chunkGo(doc Document, skipGen bool) ([]Document, error) {
	src := doc.Text
	if strings.TrimSpace(src) == "" {
		return nil, nil
	}

	parsed, err := (sourcecode.GoParser{}).Parse(string(doc.ID), []byte(src))
	if err != nil {
		return nil, err
	}
	if skipGen && parsed.Generated {
		return nil, nil
	}

	chunks := make([]Document, 0, len(parsed.Symbols))
	for _, sym := range parsed.Symbols {
		if !syntaxChunkableKind(sym.Kind) {
			continue
		}
		if sym.StartOffset < 0 || sym.EndOffset > len(src) || sym.StartOffset >= sym.EndOffset {
			continue
		}
		chunk := doc.Clone()
		chunk.Text = src[sym.StartOffset:sym.EndOffset]
		chunk.Score = 0
		if chunk.Metadata == nil {
			chunk.Metadata = Metadata{}
		}
		kind := retrievalKind(sym.Kind)
		chunk.Metadata["kind"] = kind
		chunk.Metadata["name"] = sym.Name
		chunk.Metadata["start_line"] = sym.StartLine
		chunk.Metadata["end_line"] = sym.EndLine
		if sym.Receiver != "" {
			chunk.Metadata["receiver"] = sym.Receiver
		}
		if doc.ID != "" {
			chunk.Metadata["parent_id"] = string(doc.ID)
			chunk.ID = DocumentID(fmt.Sprintf("%s:%s:%d-%d", doc.ID, sym.Name, sym.StartLine, sym.EndLine))
		}
		chunks = append(chunks, chunk)
	}
	return chunks, nil
}

func syntaxChunkableKind(kind sourcecode.SymbolKind) bool {
	return kind == sourcecode.SymbolKindFunc || kind == sourcecode.SymbolKindMethod || kind.IsType()
}

func retrievalKind(kind sourcecode.SymbolKind) string {
	if kind.IsType() {
		return string(sourcecode.SymbolKindType)
	}
	return string(kind)
}

// compile-time check that SyntaxChunker implements Chunker.
var _ Chunker = (*SyntaxChunker)(nil)
