package retrieval_test

import (
	"strings"
	"testing"

	"github.com/zarldev/zarlmono/zkit/ai/retrieval"
)

func TestSyntaxChunkerGoFiles(t *testing.T) {
	t.Run("chunks functions and types", func(t *testing.T) {
		src := `package main

func hello() string {
	return "hello"
}

type Greeter struct {
	Name string
}

func (g *Greeter) Greet() string {
	return "hello " + g.Name
}

type Namer interface {
	Name() string
}
`
		chunker := retrieval.SyntaxChunker{}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "main.go",
			Text: src,
		}})
		if err != nil {
			t.Fatal(err)
		}

		if len(chunks) != 4 {
			t.Fatalf("got %d chunks, want 4", len(chunks))
		}

		// Check chunk kinds and names.
		want := []struct {
			kind, name, receiver string
		}{
			{"func", "hello", ""},
			{"type", "Greeter", ""},
			{"method", "Greet", "*Greeter"},
			{"type", "Namer", ""},
		}
		for i, w := range want {
			c := chunks[i]
			if c.Metadata["kind"] != w.kind {
				t.Errorf("chunk %d: kind = %q, want %q", i, c.Metadata["kind"], w.kind)
			}
			if c.Metadata["name"] != w.name {
				t.Errorf("chunk %d: name = %q, want %q", i, c.Metadata["name"], w.name)
			}
			if w.receiver != "" && c.Metadata["receiver"] != w.receiver {
				t.Errorf("chunk %d: receiver = %q, want %q", i, c.Metadata["receiver"], w.receiver)
			}
			if got := c.Metadata["parent_id"]; got != "main.go" {
				t.Errorf("chunk %d: parent_id = %q, want main.go", i, got)
			}
			start, startOK := c.Metadata["start_line"].(int)
			end, endOK := c.Metadata["end_line"].(int)
			if !startOK || start < 1 {
				t.Errorf("chunk %d: start_line missing or invalid: %v", i, c.Metadata["start_line"])
			}
			if !endOK || end < start {
				t.Errorf("chunk %d: end_line missing or invalid: %v", i, c.Metadata["end_line"])
			}
		}

		// Verify chunk text is proper Go source.
		if chunks[0].Text != `func hello() string {
	return "hello"
}` {
			t.Errorf("chunk 0 text = %q", chunks[0].Text)
		}
		if chunks[3].Text != "type Namer interface {\n\tName() string\n}" {
			t.Errorf("chunk 3 text = %q", chunks[3].Text)
		}
	})

	t.Run("empty file returns no chunks", func(t *testing.T) {
		chunker := retrieval.SyntaxChunker{}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "empty.go",
			Text: "",
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) != 0 {
			t.Fatalf("got %d chunks, want 0", len(chunks))
		}
	})

	t.Run("skips forward declarations", func(t *testing.T) {
		src := `package main
func External() // no body
func Local() int { return 1 }
`
		chunker := retrieval.SyntaxChunker{}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "skip.go",
			Text: src,
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) != 1 {
			t.Fatalf("got %d chunks, want 1 (forward decl skipped)", len(chunks))
		}
		if chunks[0].Metadata["name"] != "Local" {
			t.Errorf("name = %q, want Local", chunks[0].Metadata["name"])
		}
	})

	t.Run("falls back for non-Go files", func(t *testing.T) {
		src := "def foo():\n    pass\n"
		chunker := retrieval.SyntaxChunker{Size: 4}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "script.py",
			Text: src,
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) == 0 {
			t.Fatal("fallback should have produced chunks")
		}
	})

	t.Run("falls back on parse error", func(t *testing.T) {
		chunker := retrieval.SyntaxChunker{}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "broken.go",
			Text: "package main\nfunc {",
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) != 1 {
			t.Fatalf("got %d chunks from fallback, want 1", len(chunks))
		}
	})

	t.Run("generated file is skipped", func(t *testing.T) {
		src := `// Code generated by foo; DO NOT EDIT.
package main

func GeneratedFunc() int { return 42 }
`
		chunker := retrieval.SyntaxChunker{}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "gen.go",
			Text: src,
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) != 0 {
			t.Fatalf("got %d chunks, want 0 (generated file skipped)", len(chunks))
		}
	})

	t.Run("generated file not skipped when SkipGenerated=false", func(t *testing.T) {
		src := `// Code generated by foo; DO NOT EDIT.
package main

func GeneratedFunc() int { return 42 }
`
		chunker := retrieval.SyntaxChunker{
			Languages:     []string{"go"},
			SkipGenerated: false,
		}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{ID: "gen.go",
			Text: src,
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) != 1 {
			t.Fatalf("got %d chunks, want 1 (SkipGenerated=false)", len(chunks))
		}
	})

	t.Run("language from metadata", func(t *testing.T) {
		chunker := retrieval.SyntaxChunker{
			Languages: []string{"python"},
			Size:      4,
		}
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:       "script.txt",
			Text:     "def foo():\n    pass\n",
			Metadata: retrieval.Metadata{"language": "python"},
		}})
		if err != nil {
			t.Fatal(err)
		}
		if len(chunks) == 0 {
			t.Fatal("should have produced chunks via language match")
		}
	})

	t.Run("chunker interface compile-time check", func(t *testing.T) {
		var c retrieval.Chunker = &retrieval.SyntaxChunker{}
		_ = c
	})
}

func TestSyntaxChunkerChunkFuncAdaptor(t *testing.T) {
	// Verify ChunkFunc adaptor works with SyntaxChunker.
	var c retrieval.Chunker = retrieval.ChunkFunc(
		(&retrieval.SyntaxChunker{}).Chunk,
	)
	_ = c // compile-time check only
}
func TestSyntaxChunkerMetadataPreserved(t *testing.T) {
	src := `package p
func Foo(a int) (int, error) {
	if a > 0 {
		return a * 2, nil
	}
	return 0, nil
}
`
	chunker := retrieval.SyntaxChunker{}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
		ID:       "annotated.go",
		Text:     src,
		Metadata: retrieval.Metadata{"ext": ".go", "source": "testdata"},
	}})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) != 1 {
		t.Fatalf("got %d chunks, want 1", len(chunks))
	}
	c := chunks[0]
	if c.Metadata["source"] != "testdata" {
		t.Errorf("source metadata not preserved: %v", c.Metadata["source"])
	}
	if c.Metadata["parent_id"] != "annotated.go" {
		t.Errorf("parent_id = %q", c.Metadata["parent_id"])
	}
	if c.ID == "" {
		t.Error("chunk ID is empty")
	}
}

func TestSyntaxChunkerReceiverNames(t *testing.T) {
	tests := []struct {
		src, wantReceiver string
	}{
		{`package p
type T struct{}
func (t T) M() {}
`, "T"},
		{`package p
type T struct{}
func (t *T) M() {}
`, "*T"},
	}
	chunker := retrieval.SyntaxChunker{}
	for i, tt := range tests {
		chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
			ID:   "recv.go",
			Text: tt.src,
		}})
		if err != nil {
			t.Fatal(err)
		}
		var recv string
		for _, c := range chunks {
			if c.Metadata["kind"] == "method" {
				recv, _ = c.Metadata["receiver"].(string)
			}
		}
		if recv != tt.wantReceiver {
			t.Errorf("test %d: receiver = %q, want %q", i, recv, tt.wantReceiver)
		}
	}
}

func TestSyntaxChunkerFallbackSize(t *testing.T) {
	src := "0123456789"
	chunker := retrieval.SyntaxChunker{Size: 5, Overlap: 1}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
		ID:   "data.txt",
		Text: src,
	}})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) < 2 {
		t.Fatalf("fallback with Size=5 should split %q into >=2 chunks, got %d", src, len(chunks))
	}
}

func TestSyntaxChunkerMultipleDocs(t *testing.T) {
	chunker := retrieval.SyntaxChunker{}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{
		{ID: "a.go", Text: "package p\nfunc A() int { return 1 }\n"},
		{ID: "b.go", Text: "package p\nfunc B() int { return 2 }\n"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) != 2 {
		t.Fatalf("got %d chunks, want 2", len(chunks))
	}
	if chunks[0].Metadata["parent_id"] != "a.go" {
		t.Errorf("chunk 0 parent_id = %q", chunks[0].Metadata["parent_id"])
	}
	if chunks[1].Metadata["parent_id"] != "b.go" {
		t.Errorf("chunk 1 parent_id = %q", chunks[1].Metadata["parent_id"])
	}
}

func TestSyntaxChunkerUTF8Offsets(t *testing.T) {
	src := "package p\n// 日本語コメント\nfunc F() int { return 1 }\n"
	chunker := retrieval.SyntaxChunker{}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
		ID:   "utf8.go",
		Text: src,
	}})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) != 1 {
		t.Fatalf("got %d chunks, want 1", len(chunks))
	}
	if chunks[0].Text != "func F() int { return 1 }" {
		t.Errorf("chunk text = %q", chunks[0].Text)
	}
}

func TestSyntaxChunkerImportsOnly(t *testing.T) {
	src := `package p
import "fmt"
`
	chunker := retrieval.SyntaxChunker{}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{
		ID:   "imports.go",
		Text: src,
	}})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) != 0 {
		t.Fatalf("got %d chunks, want 0", len(chunks))
	}
}

func TestSyntaxChunkerGroupedTypes(t *testing.T) {
	// Grouped type blocks must chunk each spec independently without overlap.
	src := "package p\n\ntype (\n\tA struct{ X int }\n\tB struct{ Y int }\n)\n"
	chunker := retrieval.SyntaxChunker{}
	chunks, err := chunker.Chunk(t.Context(), []retrieval.Document{{ID: "group.go", Text: src}})
	if err != nil {
		t.Fatal(err)
	}
	if len(chunks) != 2 {
		t.Fatalf("got %d chunks, want 2", len(chunks))
	}
	if chunks[0].Metadata["name"] != "A" {
		t.Errorf("chunk 0 name = %q", chunks[0].Metadata["name"])
	}
	if chunks[1].Metadata["name"] != "B" {
		t.Errorf("chunk 1 name = %q", chunks[1].Metadata["name"])
	}
	// Chunk 0 must not contain chunk 1's source.
	if strings.Contains(chunks[0].Text, "B struct") {
		t.Errorf("chunk 0 overlaps chunk 1:\n%s", chunks[0].Text)
	}
	// The full source must be covered: chunk 0 + chunk 1 should cover the
	// original text from the "type" keyword to the closing paren.
	fullText := chunks[0].Text + chunks[1].Text
	if !strings.Contains(fullText, "type (") || !strings.Contains(fullText, ")") {
		t.Errorf("combined chunks don't cover the grouped block:\nA:\n%s\nB:\n%s", chunks[0].Text, chunks[1].Text)
	}
}
