package retrieval

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
)

// SyntaxChunker splits source files by structural AST boundaries. For Go
// files it uses go/parser+go/ast — zero CGO, zero WASM, stdlib only. Files
// that fail to parse or whose language is not supported fall back to a
// TextChunker.
//
// Each chunk's metadata carries:
//
//	kind         — "func", "method", or "type"
//	name         — the declared identifier
//	receiver     — (methods only) the receiver type name
//	start_line   — 1-based line of the first declaration token
//	end_line     — 1-based line after the last declaration token
//
// The chunk Text is the exact source bytes of the declaration, extracted via
// the token.FileSet byte offsets — no reformatting, no loss.
type SyntaxChunker struct {
	// Size is the per-chunk source-byte target used only by the fallback.
	// Zero means every structural unit becomes its own chunk (no size-based
	// splitting of large declarations).
	Size int

	// Overlap is passed through to the fallback TextChunker.
	Overlap int

	// Languages lists lowercase file extensions that should be parsed
	// structurally. Default: ["go"]. Future entries ("py", "ts", "rs", etc.)
	// will route to tree-sitter backends keyed by this same field.
	Languages []string

	// SkipGenerated skips Go files detected as generated (the
	// "Code generated by" comment convention). The zero value of
	// SyntaxChunker (no Languages set) defaults to true for safety.
	// When Languages is explicitly configured, this field is used
	// as-is.
	SkipGenerated bool
}

// Chunk splits each document by structural AST boundaries.
func (c SyntaxChunker) Chunk(ctx context.Context, docs []Document) ([]Document, error) {
	// Defaults: when the caller uses the zero-value Languages (nil slice), we
	// also default SkipGenerated to true for safety. Explicit Languages
	// configuration leaves SkipGenerated as-is.
	useDefaults := c.Languages == nil
	langs := c.Languages
	if len(langs) == 0 {
		langs = []string{"go"}
	}
	langSet := make(map[string]struct{}, len(langs))
	for _, l := range langs {
		langSet[strings.ToLower(l)] = struct{}{}
	}
	skipGen := c.SkipGenerated
	if useDefaults {
		skipGen = true
	}

	// Fallback: when Size is zero we still need a working chunker for
	// non-Go files and parse errors. Use a safe minimum so
	// TextChunker never rejects input.
	fallbackSize := c.Size
	if fallbackSize <= 0 {
		fallbackSize = 2048
	}
	fallback := TextChunker{Size: fallbackSize, Overlap: c.Overlap}

	var out []Document
	for i := range docs {
		doc := &docs[i]
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		ext := c.inferExt(doc)
		if _, ok := langSet[ext]; !ok {
			chunks, err := fallback.Chunk(ctx, []Document{*doc})
			if err != nil {
				return nil, err
			}
			out = append(out, chunks...)
			continue
		}

		switch ext {
		case "go":
			chunks, err := c.chunkGo(ctx, *doc, skipGen)
			if err != nil {
				fb, fbErr := fallback.Chunk(ctx, []Document{*doc})
				if fbErr != nil {
					return nil, fmt.Errorf("syntax chunk go: %w (fallback also failed: %s)", err, fbErr.Error())
				}
				out = append(out, fb...)
				continue
			}
			out = append(out, chunks...)
		default:
			chunks, err := fallback.Chunk(ctx, []Document{*doc})
			if err != nil {
				return nil, err
			}
			out = append(out, chunks...)
		}
	}
	return out, nil
}

// inferExt returns the lowercase file extension for a document.
func (c SyntaxChunker) inferExt(doc *Document) string {
	if doc.Metadata != nil {
		if ext, ok := doc.Metadata["ext"].(string); ok && ext != "" {
			return strings.ToLower(strings.TrimPrefix(ext, "."))
		}
		if lang, ok := doc.Metadata["language"].(string); ok && lang != "" {
			return strings.ToLower(lang)
		}
	}
	id := string(doc.ID)
	if i := strings.LastIndexByte(id, '.'); i >= 0 && i < len(id)-1 {
		return strings.ToLower(id[i+1:])
	}
	return ""
}

// parseMode is the mode passed to parser.ParseFile. ParseComments gives us
// doc comments (needed for ast.IsGenerated); SkipObjectResolution skips the
// deprecated identifier-resolution pass — faster, and we don't use Scopes.
const parseMode = parser.ParseComments | parser.SkipObjectResolution

// chunkGo parses a single Go source document and returns one chunk per
// top-level func, method, or named type declaration.
func (c SyntaxChunker) chunkGo(_ context.Context, doc Document, skipGen bool) ([]Document, error) {
	src := doc.Text
	if strings.TrimSpace(src) == "" {
		return nil, nil
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, string(doc.ID), []byte(src), parseMode)
	if err != nil {
		return nil, fmt.Errorf("parse go: %w", err)
	}

	// Skip generated files — mechanically produced code is rarely useful
	// for semantic retrieval. ast.IsGenerated was added in Go 1.26.
	if skipGen && ast.IsGenerated(f) {
		return nil, nil
	}

	var chunks []Document
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			chunk := c.funcChunk(doc, src, fset, d)
			if chunk != nil {
				chunks = append(chunks, *chunk)
			}
		case *ast.GenDecl:
			n := len(d.Specs)
			for i, spec := range d.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				chunk := c.typeChunk(doc, src, fset, d, ts, i, n)
				if chunk != nil {
					chunks = append(chunks, *chunk)
				}
			}
		}
	}
	return chunks, nil
}

// funcChunk builds a chunk for *ast.FuncDecl.
func (c SyntaxChunker) funcChunk(doc Document, src string, fset *token.FileSet, fn *ast.FuncDecl) *Document {
	if fn.Body == nil {
		return nil // forward declaration — no body to chunk.
	}
	start := fset.Position(fn.Pos())
	end := fset.Position(fn.End())

	chunk := doc.Clone()
	chunk.Text = src[start.Offset:end.Offset]
	chunk.Score = 0
	if chunk.Metadata == nil {
		chunk.Metadata = Metadata{}
	}
	chunk.Metadata["start_line"] = start.Line
	chunk.Metadata["end_line"] = end.Line

	name := fn.Name.Name
	if fn.Recv != nil && len(fn.Recv.List) > 0 {
		chunk.Metadata["kind"] = "method"
		chunk.Metadata["name"] = name
		chunk.Metadata["receiver"] = c.exprName(fn.Recv.List[0].Type)
	} else {
		chunk.Metadata["kind"] = "func"
		chunk.Metadata["name"] = name
	}

	if doc.ID != "" {
		chunk.Metadata["parent_id"] = string(doc.ID)
		chunk.ID = DocumentID(fmt.Sprintf("%s:%s:%d-%d", doc.ID, name, start.Line, end.Line))
	}
	return &chunk
}

// typeChunk builds a chunk for *ast.TypeSpec. i is the spec's 0-based index
// within the parent GenDecl, n is len(GenDecl.Specs). For an ungrouped
// declaration (type Foo struct{...}) it starts at the enclosing GenDecl's
// TokPos so the chunk text includes the "type" keyword. For a grouped
// declaration (type ( A ...; B ... )) the first spec includes the "type ("
// prefix and the last includes the trailing ")" so the source is fully
// covered with no overlap.
func (c SyntaxChunker) typeChunk(doc Document, src string, fset *token.FileSet, gd *ast.GenDecl, ts *ast.TypeSpec, i, n int) *Document {
	if ts.Type == nil {
		return nil
	}

	startPos := ts.Pos()
	endPos := ts.End()

	if gd.Lparen.IsValid() {
		// Grouped: type ( A ...; B ... ). First spec owns the
		// "type (" prefix; last spec owns the trailing ")".
		if i == 0 {
			startPos = gd.TokPos
		}
		if i == n-1 {
			endPos = gd.End()
		}
	} else {
		// Ungrouped: include the "type" keyword.
		startPos = gd.TokPos
	}

	start := fset.Position(startPos)
	end := fset.Position(endPos)

	chunk := doc.Clone()
	chunk.Text = src[start.Offset:end.Offset]
	chunk.Score = 0
	if chunk.Metadata == nil {
		chunk.Metadata = Metadata{}
	}
	chunk.Metadata["kind"] = "type"
	chunk.Metadata["name"] = ts.Name.Name
	chunk.Metadata["start_line"] = start.Line
	chunk.Metadata["end_line"] = end.Line

	if doc.ID != "" {
		chunk.Metadata["parent_id"] = string(doc.ID)
		chunk.ID = DocumentID(fmt.Sprintf("%s:%s:%d-%d", doc.ID, ts.Name.Name, start.Line, end.Line))
	}
	return &chunk
}

// exprName returns a best-effort name for an ast.Expr.
func (c SyntaxChunker) exprName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + c.exprName(t.X)
	case *ast.SelectorExpr:
		return c.exprName(t.X) + "." + t.Sel.Name
	default:
		return fmt.Sprintf("%T", e)
	}
}

// compile-time check that SyntaxChunker implements Chunker.
var _ Chunker = (*SyntaxChunker)(nil)
