// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f replay_occurrence_kind_enum.go

package runner

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// ReplayOccurrenceKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ReplayOccurrenceKind struct {
	replayOccurrenceKind
}

// replayOccurrenceKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ReplayOccurrenceKind type.
type replayOccurrenceKindsContainer struct {
	MESSAGE       ReplayOccurrenceKind
	TOOLEXECUTION ReplayOccurrenceKind
}

// ReplayOccurrenceKinds is a main entry point using the ReplayOccurrenceKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ReplayOccurrenceKinds = replayOccurrenceKindsContainer{
	MESSAGE: ReplayOccurrenceKind{
		replayOccurrenceKind: message,
	},
	TOOLEXECUTION: ReplayOccurrenceKind{
		replayOccurrenceKind: toolExecution,
	},
}

// invalidReplayOccurrenceKind is an invalid sentinel value for ReplayOccurrenceKind
var invalidReplayOccurrenceKind = ReplayOccurrenceKind{
	replayOccurrenceKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r replayOccurrenceKindsContainer) allSlice() []ReplayOccurrenceKind {
	return []ReplayOccurrenceKind{
		ReplayOccurrenceKinds.MESSAGE,
		ReplayOccurrenceKinds.TOOLEXECUTION,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (r replayOccurrenceKindsContainer) All() iter.Seq[ReplayOccurrenceKind] {
	return func(yield func(ReplayOccurrenceKind) bool) {
		for _, v := range r.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseReplayOccurrenceKind = errors.New("invalid input provided to parse to ReplayOccurrenceKind")

// ParseReplayOccurrenceKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseReplayOccurrenceKind(input any) (ReplayOccurrenceKind, error) {
	switch v := input.(type) {
	case ReplayOccurrenceKind:
		return v, nil
	case string:
		if result := stringToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToReplayOccurrenceKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToReplayOccurrenceKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToReplayOccurrenceKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidReplayOccurrenceKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidReplayOccurrenceKind, fmt.Errorf("%w: invalid value %v", ErrParseReplayOccurrenceKind, input)
}

// replayOccurrenceKindsNameMap is a map of enum values to their ReplayOccurrenceKind representation
// It is used to convert string representations of enum values into their ReplayOccurrenceKind representation.
var replayOccurrenceKindsNameMap = map[string]ReplayOccurrenceKind{
	"message":        ReplayOccurrenceKinds.MESSAGE,
	"tool_execution": ReplayOccurrenceKinds.TOOLEXECUTION,
}

// stringToReplayOccurrenceKind converts a string representation of an enum value into its ReplayOccurrenceKind representation
// It returns a pointer to the ReplayOccurrenceKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToReplayOccurrenceKind(s string) *ReplayOccurrenceKind {
	if t, ok := replayOccurrenceKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToReplayOccurrenceKind converts a numeric value to a ReplayOccurrenceKind
// It returns a pointer to the ReplayOccurrenceKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToReplayOccurrenceKind[T constraints.Integer | constraints.Float](num T) *ReplayOccurrenceKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ReplayOccurrenceKinds.allSlice()) {
		return nil
	}
	result := ReplayOccurrenceKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveReplayOccurrenceKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveReplayOccurrenceKinds(f func(ReplayOccurrenceKind)) {
	for _, p := range ReplayOccurrenceKinds.allSlice() {
		f(p)
	}
}

// validReplayOccurrenceKinds is a map of enum values to their validity
var validReplayOccurrenceKinds = map[ReplayOccurrenceKind]bool{
	ReplayOccurrenceKinds.MESSAGE:       true,
	ReplayOccurrenceKinds.TOOLEXECUTION: true,
}

// IsValid checks whether the ReplayOccurrenceKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (r ReplayOccurrenceKind) IsValid() bool {
	return validReplayOccurrenceKinds[r]
}

// MarshalJSON implements the json.Marshaler interface for ReplayOccurrenceKind.
// It returns the JSON representation of the enum value as a byte slice.
func (r ReplayOccurrenceKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ReplayOccurrenceKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (r *ReplayOccurrenceKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newr, err := ParseReplayOccurrenceKind(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ReplayOccurrenceKind.
// It returns the string representation of the enum value as a byte slice
func (r ReplayOccurrenceKind) MarshalText() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ReplayOccurrenceKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReplayOccurrenceKind) UnmarshalText(by []byte) error {
	newr, err := ParseReplayOccurrenceKind(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Scan implements the database/sql.Scanner interface for ReplayOccurrenceKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (r *ReplayOccurrenceKind) Scan(value any) error {
	newr, err := ParseReplayOccurrenceKind(value)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ReplayOccurrenceKind.
// It returns the string representation of the enum value.
func (r ReplayOccurrenceKind) Value() (driver.Value, error) {
	return r.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ReplayOccurrenceKind.
// It returns the binary representation of the enum value as a byte slice.
func (r ReplayOccurrenceKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + r.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ReplayOccurrenceKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (r *ReplayOccurrenceKind) UnmarshalBinary(by []byte) error {
	newr, err := ParseReplayOccurrenceKind(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ReplayOccurrenceKind.
// It returns the string representation of the enum value.
func (r ReplayOccurrenceKind) MarshalYAML() ([]byte, error) {
	return []byte(r.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (r *ReplayOccurrenceKind) UnmarshalYAML(by []byte) error {
	newr, err := ParseReplayOccurrenceKind(by)
	if err != nil {
		return err
	}
	*r = newr
	return nil
}

// replayoccurrencekindNames is a constant string slice containing all enum values cononical absolute names
const replayoccurrencekindNames = "messagetool_execution"

// replayoccurrencekindNamesMap is a map of enum values to their canonical absolute
// name positions within the replayoccurrencekindNames string slice
var replayoccurrencekindNamesMap = map[ReplayOccurrenceKind]string{
	ReplayOccurrenceKinds.MESSAGE:       replayoccurrencekindNames[0:7],
	ReplayOccurrenceKinds.TOOLEXECUTION: replayoccurrencekindNames[7:21],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (r ReplayOccurrenceKind) String() string {
	if str, ok := replayoccurrencekindNamesMap[r]; ok {
		return str
	}
	return fmt.Sprintf("replayoccurrencekind(%d)", r.replayOccurrenceKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[message]
	_ = x[toolExecution-1]
}
