package runner

import (
	"context"
	"time"

	"github.com/zarldev/zarlmono/zkit/agent/taskscope"
	"github.com/zarldev/zarlmono/zkit/ai/llm"
)

// TaskSpec is the input to Runner.Run — everything needed to execute
// one agent task to completion (or until a terminal condition).
type TaskSpec struct {
	// ID is the task's identifier. Used for event routing.
	// Empty values are auto-generated by Run.
	ID taskscope.ID

	// Prompt is the user's request — what the task should accomplish.
	Prompt string

	// Context is pre-loaded message history (e.g. recalled memories,
	// prior turn results) that the runner prepends to the user prompt.
	// Empty is fine.
	Context []llm.Message

	// Attachments carries multimodal content for the initial user turn, such as
	// image parts attached by a UI. Prompt remains the readable text; when
	// Attachments is non-empty the runner sends Prompt as a TextPart followed by
	// these parts.
	Attachments []llm.ContentPart

	// MaxIterations caps the loop. Zero means "use the runner's
	// configured default" (set via WithMaxIterations). Negative is
	// invalid (Run errors).
	MaxIterations int

	// Thinking enables the model's reasoning mode for this task
	// (where supported). Per-task instead of per-runner so a single
	// runner can serve thinking-on and thinking-off tasks side by side.
	Thinking bool

	// Depth is the spawn-agent recursion level — 0 for top-level
	// tasks, 1 for a child spawned by a root task, and so on. Only
	// spawn-agent should set this; callers outside the runner leave
	// it zero. Surfaces in events so subscribers can render sub-agent
	// indentation.
	Depth int

	// ParentToolCallID is the ID of the tool call that initiated this
	// task — set by the spawn-agent tool when launching a sub-agent
	// so the consumer's UI can attribute the child's events back to
	// the specific parent tool call that produced it. Empty for
	// top-level tasks and for any task whose initiator is not a tool
	// dispatch. Surfaces on [ConversationStarted].
	//
	// Without this field, parallel sub-agent dispatches are
	// indistinguishable at the event boundary: their ToolStarted
	// events fire at the parent's depth carrying the parent tool
	// call ID, but the child Run that follows publishes events at
	// the new depth with a fresh task ID and no link back. The
	// model's stack-based heuristic ("bind to the most recently
	// dispatched spawn_agent") breaks under parallel fan-out
	// because both children publish their ConversationStarted in
	// arbitrary order; this field gives the binding directly.
	ParentToolCallID string

	// AgentName is set by spawn_agent when a named sub-agent profile was
	// resolved for this task. Empty means the default/parent runner.
	AgentName string

	// PromptVars are template variables the runner threads through to
	// the installed PromptSource on each Run. Sources are free to
	// ignore them.
	PromptVars PromptVars
}

// TerminalReason describes why a task ended.
type TerminalReason string

const (
	// TerminalCompleted: the model emitted no further tool calls,
	// producing a final assistant message.
	TerminalCompleted TerminalReason = "completed"
	// TerminalMaxIterations: the loop exited because it hit the
	// iteration cap without the model settling on a final answer.
	TerminalMaxIterations TerminalReason = "max_iterations"
	// TerminalError: the loop exited because of an unrecoverable error.
	TerminalError TerminalReason = "error"
	// TerminalCancelled: the loop exited because ctx was cancelled.
	TerminalCancelled TerminalReason = "cancelled"
)

// TaskResult is the output of Runner.Run.
type TaskResult struct {
	ID         taskscope.ID
	Reason     TerminalReason
	Iterations int
	Duration   time.Duration

	// FinalContent is the LLM's last assistant message (if any).
	FinalContent string

	// Messages is the full conversation history at the moment the run
	// terminated, excluding the (re-built-each-turn) system prompt.
	// REPL-style callers feed this back as TaskSpec.Context on the
	// next turn so the agent sees its own prior tool calls and the
	// model's prior answers.
	Messages []llm.Message

	// SystemPrompt is the system prompt this run used, empty when the
	// runner had no PromptSource (or it rendered empty). Messages omits
	// the system message so REPL callers don't double it; SystemPrompt
	// carries it separately so the returned transcript is self-contained
	// for post-hoc debugging without external state.
	SystemPrompt string

	// LastUsage is the token-usage snapshot from the most recent LLM
	// completion this run made (provider streams report it in the
	// final chunk). REPL-style callers use this to decide when to
	// proactively compact — i.e. before the next request would push
	// the context past its window. Nil if the run never completed an
	// LLM call (e.g. early-error paths).
	LastUsage *llm.Usage

	// TotalUsage is the sum of every iteration's reported usage —
	// the run's full token spend, not just the final iteration's
	// snapshot. Multi-iteration runs (any task with tool calls)
	// accumulate one Usage per LLM completion; LastUsage carries
	// only the last, which under-reports total cost. Callers
	// tracking session-wide spend (or sub-agent spend, via
	// spawn-agent's child Run) should prefer TotalUsage over
	// LastUsage. Nil when the run never completed an LLM call.
	TotalUsage *llm.Usage

	// Err is non-nil when Reason is TerminalError or TerminalCancelled. Nil otherwise.
	Err error
}

// ProgressUpdater receives running counters after each iteration's
// tool dispatch completes. Used to persist intermediate progress so a
// SIGKILL'd run can be reconstructed up to the last completed
// iteration. iter is the just-completed iteration index (0-based, so
// iter=0 means one iteration finished); toolCalls is the cumulative
// tool-call count across all iterations so far.
type ProgressUpdater func(ctx context.Context, iter, toolCalls int)

// defaultMaxIterations is the loop cap used when a TaskSpec's
// MaxIterations is zero and WithMaxIterations wasn't supplied.
// Conservative — callers that want runaway agents ask for it
// explicitly.
const defaultMaxIterations = 12

// toolCallJSONRecoverLimit caps consecutive in-task recoveries from
// [ErrUpstreamToolCallJSON]. Three is enough to absorb a one-off
// model hiccup (a single bad escape, a runaway code-block string)
// without giving up; more than three suggests the model is in a bad
// state that re-iterating won't escape from, so we surface it as a
// terminal error instead of looping forever.
const toolCallJSONRecoverLimit = 3

// emptyStreamRetryLimit caps consecutive in-task retries of an
// [ErrEmptyStream] iteration (the provider opened the stream then cut
// it empty — DeepSeek's gateway timing out on heavy prefill is the
// canonical case). Resets to zero on any stream that produced output.
// Three absorbs a transient gateway cut — by the retry the provider
// has usually cached the prefill so the first token lands in time —
// without spinning forever against a backend that's genuinely down.
const emptyStreamRetryLimit = 3

// rateLimitRetryLimit caps consecutive provider rate-limit retries. Rate-limit
// bodies usually include a short "try again in N.s" hint; honoring a small
// number keeps transient TPM collisions from killing long-running plans while
// still surfacing persistent quota exhaustion.
const rateLimitRetryLimit = 3

// thinkingBudgetRecoverLimit caps consecutive in-task recoveries of an
// [ErrThinkingBudget] cut (a turn that ran past the thinking-only byte
// budget without emitting content or a tool call). Each recovery injects
// a "stop reasoning, act now" nudge and retries; past the limit the model
// is clearly wedged in reasoning and we surface a terminal error rather
// than nudging forever. Resets to zero on any stream that produced output.
const thinkingBudgetRecoverLimit = 2

// defaultEmptyStreamBackoff is the base pause before the first
// empty-stream retry; subsequent retries double it (base, 2×, 4×). A
// short wait lets the provider's prefill cache settle and avoids
// hammering an overloaded gateway. Override via WithEmptyStreamBackoff
// (tests pass 0 for an immediate retry).
const defaultEmptyStreamBackoff = 500 * time.Millisecond

// defaultToolTimeout caps a single tool dispatch's wall-clock budget.
// 5 minutes is long enough for the realistic slow cases (a `go test
// ./...` on a medium project, a `cargo build` from cold cache, a
// SearXNG query against a sluggish upstream) and short enough that a
// runaway / dead tool process can't wedge the whole run. Override
// via [WithToolTimeout]; pass 0 to disable.
const defaultToolTimeout = 5 * time.Minute

// defaultIterationTimeout caps a single iteration's LLM call + stream
// drain. 5 minutes is long enough for a slow local model to finish a
// complex turn with tool calls included, and short enough to recover from
// a model wedged in runaway thinking with a diagnostic error instead of a
// SIGKILL.
const defaultIterationTimeout = 5 * time.Minute

// defaultStreamIdleTimeout caps the gap between consecutive stream chunks.
// 60 seconds catches a genuinely dead connection (provider hang) without
// false-aborting a slow-but-progressing response.
const defaultStreamIdleTimeout = 60 * time.Second
