#!/usr/bin/env python3
"""Generate the zarlcode Homebrew formula from release checksums.

Usage:
  python3 scripts/generate_homebrew_formula.py \
    --version v0.1.2 \
    --checksums artifacts/checksums.txt \
    --output homebrew/zarlcode.rb
"""

from __future__ import annotations

import argparse
from pathlib import Path

ASSET_NAMES = {
    "darwin_amd64": "zarlcode_{version}_darwin_amd64.tar.gz",
    "darwin_arm64": "zarlcode_{version}_darwin_arm64.tar.gz",
    "linux_amd64": "zarlcode_{version}_linux_amd64.tar.gz",
    "linux_arm64": "zarlcode_{version}_linux_arm64.tar.gz",
}

FORMULA_TEMPLATE = '''# Homebrew formula for zarlcode
#
# Generated by scripts/generate_homebrew_formula.py.
# Users install with:
#   brew install zarldev/tap/zarlcode

class Zarlcode < Formula
  desc "Terminal coding agent / TUI — plan first, execute second, rewind anytime"
  homepage "https://github.com/zarldev/zarlmono"
  version "{bare_version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{version}/{darwin_arm64_name}"
      sha256 "{darwin_arm64_sha}"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{version}/{darwin_amd64_name}"
      sha256 "{darwin_amd64_sha}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{version}/{linux_arm64_name}"
      sha256 "{linux_arm64_sha}"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/{version}/{linux_amd64_name}"
      sha256 "{linux_amd64_sha}"
    end
  end

  def install
    bin.install "zarlcode"
  end

  test do
    system "#{{bin}}/zarlcode", "-version"
  end
end'''


def parse_checksums(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line:
            continue
        sha, name = line.split(None, 1)
        values[name] = sha
    return values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True, help="Release version, e.g. v0.1.2")
    parser.add_argument("--checksums", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    version = args.version
    bare_version = version.removeprefix("v")
    checksums = parse_checksums(args.checksums)

    names = {key: value.format(version=version) for key, value in ASSET_NAMES.items()}
    missing = [name for name in names.values() if name not in checksums]
    if missing:
        raise SystemExit(f"missing checksum entries: {', '.join(missing)}")

    rendered = FORMULA_TEMPLATE.format(
        version=version,
        bare_version=bare_version,
        darwin_amd64_name=names["darwin_amd64"],
        darwin_amd64_sha=checksums[names["darwin_amd64"]],
        darwin_arm64_name=names["darwin_arm64"],
        darwin_arm64_sha=checksums[names["darwin_arm64"]],
        linux_amd64_name=names["linux_amd64"],
        linux_amd64_sha=checksums[names["linux_amd64"]],
        linux_arm64_name=names["linux_arm64"],
        linux_arm64_sha=checksums[names["linux_arm64"]],
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
