// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f kind_enum.go

package transcript

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// EntryKind is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type EntryKind struct {
	entryKind
}

// entryKindsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the EntryKind type.
type entryKindsContainer struct {
	ENTRYUSERMESSAGE      EntryKind
	ENTRYQUEUEDUSER       EntryKind
	ENTRYASSISTANTMESSAGE EntryKind
	ENTRYREASONING        EntryKind
	ENTRYTOOLCALL         EntryKind
	ENTRYDIFF             EntryKind
	ENTRYPLAN             EntryKind
	ENTRYSKILLS           EntryKind
	ENTRYSUBAGENT         EntryKind
	ENTRYNOTICE           EntryKind
}

// EntryKinds is a main entry point using the EntryKind type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var EntryKinds = entryKindsContainer{
	ENTRYUSERMESSAGE: EntryKind{
		entryKind: entryUserMessage,
	},
	ENTRYQUEUEDUSER: EntryKind{
		entryKind: entryQueuedUser,
	},
	ENTRYASSISTANTMESSAGE: EntryKind{
		entryKind: entryAssistantMessage,
	},
	ENTRYREASONING: EntryKind{
		entryKind: entryReasoning,
	},
	ENTRYTOOLCALL: EntryKind{
		entryKind: entryToolCall,
	},
	ENTRYDIFF: EntryKind{
		entryKind: entryDiff,
	},
	ENTRYPLAN: EntryKind{
		entryKind: entryPlan,
	},
	ENTRYSKILLS: EntryKind{
		entryKind: entrySkills,
	},
	ENTRYSUBAGENT: EntryKind{
		entryKind: entrySubagent,
	},
	ENTRYNOTICE: EntryKind{
		entryKind: entryNotice,
	},
}

// invalidEntryKind is an invalid sentinel value for EntryKind
var invalidEntryKind = EntryKind{
	entryKind: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e entryKindsContainer) allSlice() []EntryKind {
	return []EntryKind{
		EntryKinds.ENTRYUSERMESSAGE,
		EntryKinds.ENTRYQUEUEDUSER,
		EntryKinds.ENTRYASSISTANTMESSAGE,
		EntryKinds.ENTRYREASONING,
		EntryKinds.ENTRYTOOLCALL,
		EntryKinds.ENTRYDIFF,
		EntryKinds.ENTRYPLAN,
		EntryKinds.ENTRYSKILLS,
		EntryKinds.ENTRYSUBAGENT,
		EntryKinds.ENTRYNOTICE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (e entryKindsContainer) All() iter.Seq[EntryKind] {
	return func(yield func(EntryKind) bool) {
		for _, v := range e.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseEntryKind = errors.New("invalid input provided to parse to EntryKind")

// ParseEntryKind parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseEntryKind(input any) (EntryKind, error) {
	switch v := input.(type) {
	case EntryKind:
		return v, nil
	case string:
		if result := stringToEntryKind(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToEntryKind(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToEntryKind(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToEntryKind(v); result != nil {
			return *result, nil
		}
	default:
		return invalidEntryKind, fmt.Errorf("invalid type %T", input)
	}
	return invalidEntryKind, fmt.Errorf("%w: invalid value %v", ErrParseEntryKind, input)
}

// entryKindsNameMap is a map of enum values to their EntryKind representation
// It is used to convert string representations of enum values into their EntryKind representation.
var entryKindsNameMap = map[string]EntryKind{
	"user_message":      EntryKinds.ENTRYUSERMESSAGE,
	"queued_user":       EntryKinds.ENTRYQUEUEDUSER,
	"assistant_message": EntryKinds.ENTRYASSISTANTMESSAGE,
	"reasoning":         EntryKinds.ENTRYREASONING,
	"tool_call":         EntryKinds.ENTRYTOOLCALL,
	"diff":              EntryKinds.ENTRYDIFF,
	"plan":              EntryKinds.ENTRYPLAN,
	"skills":            EntryKinds.ENTRYSKILLS,
	"subagent":          EntryKinds.ENTRYSUBAGENT,
	"notice":            EntryKinds.ENTRYNOTICE,
}

// stringToEntryKind converts a string representation of an enum value into its EntryKind representation
// It returns a pointer to the EntryKind representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToEntryKind(s string) *EntryKind {
	if t, ok := entryKindsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToEntryKind converts a numeric value to a EntryKind
// It returns a pointer to the EntryKind representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToEntryKind[T constraints.Integer | constraints.Float](num T) *EntryKind {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(EntryKinds.allSlice()) {
		return nil
	}
	result := EntryKinds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveEntryKinds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveEntryKinds(f func(EntryKind)) {
	for _, p := range EntryKinds.allSlice() {
		f(p)
	}
}

// validEntryKinds is a map of enum values to their validity
var validEntryKinds = map[EntryKind]bool{
	EntryKinds.ENTRYUSERMESSAGE:      true,
	EntryKinds.ENTRYQUEUEDUSER:       true,
	EntryKinds.ENTRYASSISTANTMESSAGE: true,
	EntryKinds.ENTRYREASONING:        true,
	EntryKinds.ENTRYTOOLCALL:         true,
	EntryKinds.ENTRYDIFF:             true,
	EntryKinds.ENTRYPLAN:             true,
	EntryKinds.ENTRYSKILLS:           true,
	EntryKinds.ENTRYSUBAGENT:         true,
	EntryKinds.ENTRYNOTICE:           true,
}

// IsValid checks whether the EntryKinds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (e EntryKind) IsValid() bool {
	return validEntryKinds[e]
}

// MarshalJSON implements the json.Marshaler interface for EntryKind.
// It returns the JSON representation of the enum value as a byte slice.
func (e EntryKind) MarshalJSON() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for EntryKind.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (e *EntryKind) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newe, err := ParseEntryKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for EntryKind.
// It returns the string representation of the enum value as a byte slice
func (e EntryKind) MarshalText() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EntryKind.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EntryKind) UnmarshalText(by []byte) error {
	newe, err := ParseEntryKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Scan implements the database/sql.Scanner interface for EntryKind.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (e *EntryKind) Scan(value any) error {
	newe, err := ParseEntryKind(value)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// Value implements the database/sql/driver.Valuer interface for EntryKind.
// It returns the string representation of the enum value.
func (e EntryKind) Value() (driver.Value, error) {
	return e.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for EntryKind.
// It returns the binary representation of the enum value as a byte slice.
func (e EntryKind) MarshalBinary() ([]byte, error) {
	return []byte("\"" + e.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for EntryKind.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (e *EntryKind) UnmarshalBinary(by []byte) error {
	newe, err := ParseEntryKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for EntryKind.
// It returns the string representation of the enum value.
func (e EntryKind) MarshalYAML() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (e *EntryKind) UnmarshalYAML(by []byte) error {
	newe, err := ParseEntryKind(by)
	if err != nil {
		return err
	}
	*e = newe
	return nil
}

// entrykindNames is a constant string slice containing all enum values cononical absolute names
const entrykindNames = "user_messagequeued_userassistant_messagereasoningtool_calldiffplanskillssubagentnotice"

// entrykindNamesMap is a map of enum values to their canonical absolute
// name positions within the entrykindNames string slice
var entrykindNamesMap = map[EntryKind]string{
	EntryKinds.ENTRYUSERMESSAGE:      entrykindNames[0:12],
	EntryKinds.ENTRYQUEUEDUSER:       entrykindNames[12:23],
	EntryKinds.ENTRYASSISTANTMESSAGE: entrykindNames[23:40],
	EntryKinds.ENTRYREASONING:        entrykindNames[40:49],
	EntryKinds.ENTRYTOOLCALL:         entrykindNames[49:58],
	EntryKinds.ENTRYDIFF:             entrykindNames[58:62],
	EntryKinds.ENTRYPLAN:             entrykindNames[62:66],
	EntryKinds.ENTRYSKILLS:           entrykindNames[66:72],
	EntryKinds.ENTRYSUBAGENT:         entrykindNames[72:80],
	EntryKinds.ENTRYNOTICE:           entrykindNames[80:86],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (e EntryKind) String() string {
	if str, ok := entrykindNamesMap[e]; ok {
		return str
	}
	return fmt.Sprintf("entrykind(%d)", e.entryKind)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [10]struct{}
	_ = x[entryUserMessage]
	_ = x[entryQueuedUser-1]
	_ = x[entryAssistantMessage-2]
	_ = x[entryReasoning-3]
	_ = x[entryToolCall-4]
	_ = x[entryDiff-5]
	_ = x[entryPlan-6]
	_ = x[entrySkills-7]
	_ = x[entrySubagent-8]
	_ = x[entryNotice-9]
}
