// Code generated by goenums v0.4.9; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f persistence_enum.go

package transcript

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// Persistence is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type Persistence struct {
	persistence
}

// persistencesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the Persistence type.
type persistencesContainer struct {
	PERSISTENCENONE      Persistence
	PERSISTENCEDEBOUNCED Persistence
	PERSISTENCEIMMEDIATE Persistence
}

// Persistences is a main entry point using the Persistence type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Persistences = persistencesContainer{
	PERSISTENCENONE: Persistence{
		persistence: persistenceNone,
	},
	PERSISTENCEDEBOUNCED: Persistence{
		persistence: persistenceDebounced,
	},
	PERSISTENCEIMMEDIATE: Persistence{
		persistence: persistenceImmediate,
	},
}

// invalidPersistence is an invalid sentinel value for Persistence
var invalidPersistence = Persistence{
	persistence: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (p persistencesContainer) allSlice() []Persistence {
	return []Persistence{
		Persistences.PERSISTENCENONE,
		Persistences.PERSISTENCEDEBOUNCED,
		Persistences.PERSISTENCEIMMEDIATE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (p persistencesContainer) All() iter.Seq[Persistence] {
	return func(yield func(Persistence) bool) {
		for _, v := range p.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParsePersistence = errors.New("invalid input provided to parse to Persistence")

// ParsePersistence parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParsePersistence(input any) (Persistence, error) {
	switch v := input.(type) {
	case Persistence:
		return v, nil
	case string:
		if result := stringToPersistence(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToPersistence(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToPersistence(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToPersistence(v); result != nil {
			return *result, nil
		}
	default:
		return invalidPersistence, fmt.Errorf("invalid type %T", input)
	}
	return invalidPersistence, fmt.Errorf("%w: invalid value %v", ErrParsePersistence, input)
}

// persistencesNameMap is a map of enum values to their Persistence representation
// It is used to convert string representations of enum values into their Persistence representation.
var persistencesNameMap = map[string]Persistence{
	"none":      Persistences.PERSISTENCENONE,
	"debounced": Persistences.PERSISTENCEDEBOUNCED,
	"immediate": Persistences.PERSISTENCEIMMEDIATE,
}

// stringToPersistence converts a string representation of an enum value into its Persistence representation
// It returns a pointer to the Persistence representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToPersistence(s string) *Persistence {
	if t, ok := persistencesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToPersistence converts a numeric value to a Persistence
// It returns a pointer to the Persistence representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToPersistence[T constraints.Integer | constraints.Float](num T) *Persistence {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(Persistences.allSlice()) {
		return nil
	}
	result := Persistences.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustivePersistences iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustivePersistences(f func(Persistence)) {
	for _, p := range Persistences.allSlice() {
		f(p)
	}
}

// validPersistences is a map of enum values to their validity
var validPersistences = map[Persistence]bool{
	Persistences.PERSISTENCENONE:      true,
	Persistences.PERSISTENCEDEBOUNCED: true,
	Persistences.PERSISTENCEIMMEDIATE: true,
}

// IsValid checks whether the Persistences value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (p Persistence) IsValid() bool {
	return validPersistences[p]
}

// MarshalJSON implements the json.Marshaler interface for Persistence.
// It returns the JSON representation of the enum value as a byte slice.
func (p Persistence) MarshalJSON() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Persistence.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (p *Persistence) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newp, err := ParsePersistence(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Persistence.
// It returns the string representation of the enum value as a byte slice
func (p Persistence) MarshalText() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Persistence.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (p *Persistence) UnmarshalText(by []byte) error {
	newp, err := ParsePersistence(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// Scan implements the database/sql.Scanner interface for Persistence.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (p *Persistence) Scan(value any) error {
	newp, err := ParsePersistence(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// Value implements the database/sql/driver.Valuer interface for Persistence.
// It returns the string representation of the enum value.
func (p Persistence) Value() (driver.Value, error) {
	return p.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Persistence.
// It returns the binary representation of the enum value as a byte slice.
func (p Persistence) MarshalBinary() ([]byte, error) {
	return []byte("\"" + p.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Persistence.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (p *Persistence) UnmarshalBinary(by []byte) error {
	newp, err := ParsePersistence(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for Persistence.
// It returns the string representation of the enum value.
func (p Persistence) MarshalYAML() ([]byte, error) {
	return []byte(p.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (p *Persistence) UnmarshalYAML(by []byte) error {
	newp, err := ParsePersistence(by)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

// persistenceNames is a constant string slice containing all enum values cononical absolute names
const persistenceNames = "nonedebouncedimmediate"

// persistenceNamesMap is a map of enum values to their canonical absolute
// name positions within the persistenceNames string slice
var persistenceNamesMap = map[Persistence]string{
	Persistences.PERSISTENCENONE:      persistenceNames[0:4],
	Persistences.PERSISTENCEDEBOUNCED: persistenceNames[4:13],
	Persistences.PERSISTENCEIMMEDIATE: persistenceNames[13:22],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (p Persistence) String() string {
	if str, ok := persistenceNamesMap[p]; ok {
		return str
	}
	return fmt.Sprintf("persistence(%d)", p.persistence)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[persistenceNone]
	_ = x[persistenceDebounced-1]
	_ = x[persistenceImmediate-2]
}
